import type { CollectionSlug, Verse } from './catalogo';

type C = CollectionSlug;
const v = (slug: string, reference: string, collection: C, popularPhrase: string, wave = 1): Verse => ({
  slug,
  reference,
  collection,
  popularPhrase,
  wave,
});

/**
 * Todos los versículos del catálogo, ordenados por prioridad de búsqueda.
 * `wave` es la oleada de publicación (ver PUBLISHED_WAVE en catalogo.ts).
 * El contenido de cada uno está en contenido/versiculos/{slug}.md.
 */
export const allVerses: Verse[] = [
  v('juan-3-16', 'Juan 3:16', 'amor', 'De tal manera amó Dios al mundo'),
  v('filipenses-4-13', 'Filipenses 4:13', 'fe-y-valor', 'Todo lo puedo en Cristo'),
  v('salmo-23', 'Salmo 23', 'confianza', 'El Señor es mi pastor'),
  v('jeremias-29-11', 'Jeremías 29:11', 'esperanza', 'Yo sé los planes que tengo para ti'),
  v('josue-1-9', 'Josué 1:9', 'fe-y-valor', 'Sé fuerte y valiente'),
  v('isaias-41-10', 'Isaías 41:10', 'fe-y-valor', 'No temas, yo estoy contigo'),
  v('proverbios-3-5', 'Proverbios 3:5', 'confianza', 'Confía en el Señor de todo corazón'),
  v('salmo-91', 'Salmo 91', 'esperanza', 'Al abrigo del Altísimo'),
  v('romanos-8-28', 'Romanos 8:28', 'esperanza', 'Todo ayuda a bien'),
  v('genesis-1-1', 'Génesis 1:1', 'identidad', 'En el principio creó Dios'),
  v('salmo-23-4', 'Salmo 23:4', 'confianza', 'No temeré mal alguno'),
  v('mateo-6-33', 'Mateo 6:33', 'sabiduria', 'Buscad primero el reino de Dios'),
  v('isaias-40-31', 'Isaías 40:31', 'fe-y-valor', 'Levantarán alas como las águilas'),
  v('filipenses-4-6', 'Filipenses 4:6', 'confianza', 'Por nada estéis afanosos'),
  v('1-corintios-13', '1 Corintios 13', 'amor', 'El amor es paciente'),
  v('salmo-121-2', 'Salmo 121:2', 'esperanza', 'Mi socorro viene del Señor'),
  v('romanos-12-2', 'Romanos 12:2', 'sabiduria', 'Transformaos'),
  v('juan-14-6', 'Juan 14:6', 'identidad', 'El camino, la verdad y la vida'),
  v('salmo-46-1', 'Salmo 46:1', 'esperanza', 'Dios es nuestro amparo y fortaleza'),
  v('mateo-11-28', 'Mateo 11:28', 'confianza', 'Venid a mí'),
  v('2-timoteo-1-7', '2 Timoteo 1:7', 'fe-y-valor', 'Poder, amor y dominio propio'),
  v('salmo-119-105', 'Salmo 119:105', 'sabiduria', 'Lámpara es a mis pies tu palabra'),
  v('galatas-5-22', 'Gálatas 5:22', 'amor', 'Amor, gozo, paz'),
  v('1-tesalonicenses-5-16-18', '1 Tesalonicenses 5:16-18', 'alabanza', 'Dad gracias en todo'),
  v('salmo-27-1', 'Salmo 27:1', 'fe-y-valor', '¿De quién temeré?'),
  v('hebreos-11-1', 'Hebreos 11:1', 'esperanza', 'La certeza de lo que se espera'),
  v('efesios-2-8', 'Efesios 2:8', 'gracia', 'Por gracia sois salvos'),
  v('1-juan-4-8', '1 Juan 4:8', 'amor', 'Dios es amor'),
  v('proverbios-16-3', 'Proverbios 16:3', 'confianza', 'Encomienda al Señor tus obras'),
  v('juan-10-10', 'Juan 10:10', 'identidad', 'Vida en abundancia'),
  v('apocalipsis-3-20', 'Apocalipsis 3:20', 'identidad', 'Estoy a la puerta y llamo'),
  v('marcos-11-24', 'Marcos 11:24', 'fe-y-valor', 'Creed que lo recibiréis'),
  v('romanos-8-31', 'Romanos 8:31', 'fe-y-valor', 'Si Dios es por nosotros'),
  v('santiago-1-5', 'Santiago 1:5', 'sabiduria', 'Pídala a Dios'),
  v('jeremias-33-3', 'Jeremías 33:3', 'confianza', 'Clama a mí, y yo te responderé'),
  v('salmo-37-4', 'Salmo 37:4', 'alabanza', 'Deléitate en el Señor'),
  v('mateo-28-19', 'Mateo 28:19', 'identidad', 'Id y haced discípulos'),
  v('colosenses-3-23', 'Colosenses 3:23', 'sabiduria', 'Hacedlo de corazón'),
  v('2-corintios-5-17', '2 Corintios 5:17', 'identidad', 'Nueva criatura es'),
  v('deuteronomio-31-6', 'Deuteronomio 31:6', 'fe-y-valor', 'Esforzaos y cobrad ánimo'),
  v('salmo-100-1', 'Salmo 100:1', 'alabanza', 'Cantad alegres a Dios'),
  v('salmo-34-8', 'Salmo 34:8', 'confianza', 'Gustad, y ved que es bueno'),
  v('salmo-139-14', 'Salmo 139:14', 'alabanza', 'Formidables, maravillosas son tus obras'),
  v('romanos-5-8', 'Romanos 5:8', 'amor', 'Cristo murió por nosotros'),
  v('mateo-7-7', 'Mateo 7:7', 'confianza', 'Pedid, y se os dará'),
  v('numeros-6-24', 'Números 6:24', 'alabanza', 'El Señor te bendiga y te guarde'),
  v('proverbios-4-23', 'Proverbios 4:23', 'sabiduria', 'Guarda tu corazón'),
  v('salmo-118-24', 'Salmo 118:24', 'alabanza', 'Este es el día que hizo el Señor'),
  v('galatas-2-20', 'Gálatas 2:20', 'identidad', 'Ya no vivo yo, vive Cristo en mí'),
  v('juan-8-32', 'Juan 8:32', 'identidad', 'La verdad os hará libres'),
  v('salmo-1-1', 'Salmo 1:1', 'sabiduria', 'Bienaventurado el varón'),
  v('romanos-10-9', 'Romanos 10:9', 'gracia', 'Jesús es el Señor'),
  v('juan-15-5', 'Juan 15:5', 'identidad', 'Yo soy la vid'),
  v('efesios-6-10', 'Efesios 6:10', 'fe-y-valor', 'Fortaleceos en el Señor'),
  v('salmo-51-10', 'Salmo 51:10', 'gracia', 'Crea en mí un corazón limpio'),
  v('mateo-5-14', 'Mateo 5:14', 'identidad', 'Sois la luz del mundo'),
  v('lucas-1-37', 'Lucas 1:37', 'fe-y-valor', 'Nada hay imposible para Dios'),
  v('salmo-103-2', 'Salmo 103:2', 'alabanza', 'Bendice, alma mía, al Señor'),
  v('juan-1-1', 'Juan 1:1', 'identidad', 'En el principio era el Verbo'),
  v('1-pedro-5-7', '1 Pedro 5:7', 'confianza', 'Él tiene cuidado de vosotros'),
  v('proverbios-18-10', 'Proverbios 18:10', 'esperanza', 'Torre fuerte es el nombre del Señor'),
  v('efesios-3-20', 'Efesios 3:20', 'fe-y-valor', 'Mucho más abundantemente'),
  v('salmo-121-7', 'Salmo 121:7', 'esperanza', 'El Señor te guardará de todo mal'),
  v('juan-11-25', 'Juan 11:25', 'esperanza', 'Yo soy la resurrección y la vida'),
  v('santiago-1-22', 'Santiago 1:22', 'sabiduria', 'Hacedores de la palabra'),
  v('2-corintios-5-7', '2 Corintios 5:7', 'fe-y-valor', 'Por fe andamos, no por vista'),
  v('hechos-1-8', 'Hechos 1:8', 'fe-y-valor', 'Recibiréis poder'),
  v('salmo-119-11', 'Salmo 119:11', 'sabiduria', 'En mi corazón he guardado tus dichos'),
  v('proverbios-3-7', 'Proverbios 3:7', 'sabiduria', 'Teme al Señor y apártate del mal'),
  v('mateo-18-20', 'Mateo 18:20', 'identidad', 'Allí estoy yo en medio de ellos'),
  v('hebreos-12-1', 'Hebreos 12:1', 'fe-y-valor', 'Corramos con paciencia la carrera'),
  v('salmo-37-5', 'Salmo 37:5', 'confianza', 'Encomienda al Señor tu camino'),
  v('efesios-4-32', 'Efesios 4:32', 'amor', 'Perdonándoos unos a otros'),
  v('salmo-139-1', 'Salmo 139:1', 'identidad', 'Tú me has examinado y conocido'),
  v('jeremias-17-7', 'Jeremías 17:7', 'confianza', 'Bendito el que confía en el Señor'),
  v('deuteronomio-6-5', 'Deuteronomio 6:5', 'amor', 'Amarás al Señor tu Dios'),
  v('1-corintios-10-13', '1 Corintios 10:13', 'fe-y-valor', 'Fiel es Dios'),
  v('mateo-6-14', 'Mateo 6:14', 'amor', 'Si perdonáis a los hombres sus ofensas'),
  v('salmo-23-6', 'Salmo 23:6', 'confianza', 'El bien y la misericordia me seguirán'),
  v('hechos-16-31', 'Hechos 16:31', 'gracia', 'Cree en el Señor Jesucristo'),
  v('juan-15-13', 'Juan 15:13', 'amor', 'Nadie tiene mayor amor que este'),
  v('romanos-8-39', 'Romanos 8:39', 'amor', 'Nada nos podrá separar del amor de Dios'),
  v('proverbios-22-6', 'Proverbios 22:6', 'sabiduria', 'Instruye al niño en su camino'),
  v('salmo-143-8', 'Salmo 143:8', 'alabanza', 'Hazme oír por la mañana tu misericordia'),
  v('romanos-15-13', 'Romanos 15:13', 'esperanza', 'El Dios de esperanza'),
  v('isaias-53-5', 'Isaías 53:5', 'gracia', 'Por su llaga fuimos nosotros curados'),
  v('salmo-91-11', 'Salmo 91:11', 'esperanza', 'A sus ángeles mandará cerca de ti'),
  v('mateo-22-39', 'Mateo 22:39', 'amor', 'Amarás a tu prójimo como a ti mismo'),
  v('1-juan-1-9', '1 Juan 1:9', 'gracia', 'Fiel y justo para perdonar'),
  v('salmo-19-14', 'Salmo 19:14', 'sabiduria', 'Sean gratos los dichos de mi boca'),
  v('1-corintios-16-14', '1 Corintios 16:14', 'amor', 'Todo con amor'),
  v('salmo-42-1', 'Salmo 42:1', 'confianza', 'Como el ciervo brama por las aguas'),
  v('proverbios-31-30', 'Proverbios 31:30', 'sabiduria', 'La mujer que teme al Señor'),
  v('deuteronomio-31-8', 'Deuteronomio 31:8', 'fe-y-valor', 'El Señor va delante de ti'),
  v('1-juan-5-14', '1 Juan 5:14', 'confianza', 'Él nos oye'),
  v('salmo-62-1', 'Salmo 62:1', 'esperanza', 'En Dios solamente está acallada mi alma'),
  v('mateo-5-3', 'Mateo 5:3', 'gracia', 'Bienaventurados los pobres en espíritu'),
  v('juan-8-12', 'Juan 8:12', 'identidad', 'Yo soy la luz del mundo'),
  v('salmo-118-1', 'Salmo 118:1', 'alabanza', 'Para siempre es su misericordia'),
  v('apocalipsis-21-4', 'Apocalipsis 21:4', 'esperanza', 'Enjugará toda lágrima'),
  v('juan-16-33', 'Juan 16:33', 'fe-y-valor', 'Tened valor, yo he vencido al mundo'),
  v('salmo-119-89', 'Salmo 119:89', 'sabiduria', 'Para siempre, oh Señor, permanece tu palabra', 2),
  v('mateo-11-29', 'Mateo 11:29', 'identidad', 'Soy manso y humilde de corazón', 2),
  v('proverbios-16-9', 'Proverbios 16:9', 'confianza', 'El corazón del hombre piensa su camino', 2),
  v('1-corintios-13-8', '1 Corintios 13:8', 'amor', 'El amor nunca deja de ser', 2),
  v('salmo-119-130', 'Salmo 119:130', 'sabiduria', 'La exposición de tus palabras alumbra', 2),
  v('galatas-6-9', 'Gálatas 6:9', 'fe-y-valor', 'No nos cansemos de hacer el bien', 2),
  v('2-corintios-12-9', '2 Corintios 12:9', 'gracia', 'Bástate mi gracia', 2),
  v('salmo-46-10', 'Salmo 46:10', 'confianza', 'Estad quietos, y conoced que yo soy Dios', 2),
  v('mateo-5-8', 'Mateo 5:8', 'gracia', 'Los de limpio corazón verán a Dios', 2),
  v('proverbios-31-25', 'Proverbios 31:25', 'identidad', 'Fuerza y honor son su vestidura', 2),
  v('juan-14-27', 'Juan 14:27', 'esperanza', 'La paz os dejo, mi paz os doy', 2),
  v('isaias-43-2', 'Isaías 43:2', 'fe-y-valor', 'Cuando pases por las aguas, yo estaré contigo', 2),
  v('salmo-121-8', 'Salmo 121:8', 'esperanza', 'Guardará tu salida y tu entrada', 2),
  v('romanos-12-21', 'Romanos 12:21', 'fe-y-valor', 'Vence con el bien el mal', 2),
  v('1-juan-4-19', '1 Juan 4:19', 'amor', 'Él nos amó primero', 2),
  v('filipenses-4-19', 'Filipenses 4:19', 'confianza', 'Mi Dios suplirá todo lo que os falte', 2),
  v('mateo-6-34', 'Mateo 6:34', 'confianza', 'No os afanéis por el día de mañana', 2),
  v('proverbios-17-17', 'Proverbios 17:17', 'amor', 'En todo tiempo ama el amigo', 2),
  v('salmo-34-4', 'Salmo 34:4', 'confianza', 'Me libró de todos mis temores', 2),
  v('2-timoteo-4-7', '2 Timoteo 4:7', 'fe-y-valor', 'He peleado la buena batalla', 2),
  v('juan-3-17', 'Juan 3:17', 'gracia', 'Para que el mundo sea salvo por él', 2),
  v('hebreos-13-8', 'Hebreos 13:8', 'esperanza', 'El mismo ayer, y hoy, y por los siglos', 2),
  v('salmo-37-23', 'Salmo 37:23', 'confianza', 'Por el Señor son ordenados los pasos', 2),
  v('1-corintios-16-13', '1 Corintios 16:13', 'fe-y-valor', 'Velad, estad firmes en la fe', 2),
  v('isaias-26-3', 'Isaías 26:3', 'confianza', 'Tú guardarás en completa paz', 2),
  v('efesios-2-10', 'Efesios 2:10', 'identidad', 'Somos hechura suya', 2),
  v('salmo-119-114', 'Salmo 119:114', 'confianza', 'Mi escondedero y mi escudo eres tú', 2),
  v('proverbios-18-24', 'Proverbios 18:24', 'amor', 'Hay amigo más unido que un hermano', 2),
  v('mateo-5-9', 'Mateo 5:9', 'identidad', 'Bienaventurados los pacificadores', 2),
  v('romanos-8-18', 'Romanos 8:18', 'esperanza', 'No son comparables con la gloria venidera', 2),
  v('salmo-84-11', 'Salmo 84:11', 'alabanza', 'Sol y escudo es el Señor Dios', 2),
  v('colosenses-3-2', 'Colosenses 3:2', 'sabiduria', 'Poned la mira en las cosas de arriba', 2),
  v('1-pedro-2-9', '1 Pedro 2:9', 'identidad', 'Linaje escogido, real sacerdocio', 2),
  v('salmo-91-4', 'Salmo 91:4', 'esperanza', 'Debajo de sus alas estarás seguro', 2),
  v('proverbios-28-1', 'Proverbios 28:1', 'fe-y-valor', 'El justo está confiado como un león', 2),
  v('mateo-19-26', 'Mateo 19:26', 'fe-y-valor', 'Para Dios todo es posible', 2),
  v('isaias-54-17', 'Isaías 54:17', 'fe-y-valor', 'Ninguna arma forjada contra ti prosperará', 2),
  v('salmo-139-23', 'Salmo 139:23', 'sabiduria', 'Pruébame y conoce mis pensamientos', 2),
  v('romanos-12-12', 'Romanos 12:12', 'esperanza', 'Gozosos en la esperanza', 2),
  v('1-juan-3-1', '1 Juan 3:1', 'identidad', 'Mirad cuál amor nos ha dado el Padre', 2),
  v('salmo-63-1', 'Salmo 63:1', 'alabanza', 'De madrugada te buscaré', 2),
  v('proverbios-15-1', 'Proverbios 15:1', 'sabiduria', 'La blanda respuesta quita la ira', 2),
  v('mateo-6-21', 'Mateo 6:21', 'sabiduria', 'Allí estará también vuestro corazón', 2),
  v('filipenses-1-6', 'Filipenses 1:6', 'esperanza', 'El que comenzó en vosotros la buena obra', 2),
  v('salmo-103-8', 'Salmo 103:8', 'gracia', 'Lento para la ira, y grande en misericordia', 2),
  v('jeremias-31-3', 'Jeremías 31:3', 'amor', 'Con amor eterno te he amado', 2),
  v('2-corintios-3-17', '2 Corintios 3:17', 'identidad', 'Donde está el Espíritu, allí hay libertad', 2),
  v('salmo-118-6', 'Salmo 118:6', 'fe-y-valor', 'El Señor está conmigo; no temeré', 2),
  v('juan-15-12', 'Juan 15:12', 'amor', 'Como yo os he amado', 2),
  v('proverbios-19-21', 'Proverbios 19:21', 'sabiduria', 'El consejo del Señor permanecerá', 2),
  v('mateo-5-5', 'Mateo 5:5', 'identidad', 'Los mansos recibirán la tierra por heredad', 2),
  v('efesios-5-8', 'Efesios 5:8', 'identidad', 'Andad como hijos de luz', 2),
  v('salmo-30-5', 'Salmo 30:5', 'esperanza', 'A la mañana vendrá la alegría', 2),
  v('romanos-1-16', 'Romanos 1:16', 'fe-y-valor', 'No me avergüenzo del evangelio', 2),
  v('1-corintios-15-57', '1 Corintios 15:57', 'alabanza', 'Gracias a Dios, que nos da la victoria', 2),
  v('salmo-119-160', 'Salmo 119:160', 'sabiduria', 'La suma de tu palabra es verdad', 2),
  v('isaias-12-2', 'Isaías 12:2', 'confianza', 'Dios es mi salvación', 2),
  v('proverbios-27-17', 'Proverbios 27:17', 'amor', 'Hierro con hierro se afila', 2),
  v('mateo-7-12', 'Mateo 7:12', 'amor', 'Así también haced vosotros con ellos', 2),
  v('santiago-1-17', 'Santiago 1:17', 'alabanza', 'Todo don perfecto desciende de lo alto', 2),
  v('salmo-16-11', 'Salmo 16:11', 'alabanza', 'En tu presencia hay plenitud de gozo', 2),
  v('1-pedro-4-8', '1 Pedro 4:8', 'amor', 'Tened entre vosotros ferviente amor', 2),
  v('juan-6-35', 'Juan 6:35', 'identidad', 'Yo soy el pan de vida', 2),
  v('proverbios-16-24', 'Proverbios 16:24', 'sabiduria', 'Panal de miel son las palabras suaves', 2),
  v('romanos-8-32', 'Romanos 8:32', 'gracia', 'El que no escatimó ni a su propio Hijo', 2),
  v('filipenses-3-14', 'Filipenses 3:14', 'fe-y-valor', 'Prosigo a la meta', 2),
  v('mateo-24-35', 'Mateo 24:35', 'esperanza', 'Mis palabras no pasarán', 2),
  v('1-tesalonicenses-5-11', '1 Tesalonicenses 5:11', 'amor', 'Animaos unos a otros, y edificaos', 2),
  v('salmo-139-7', 'Salmo 139:7', 'confianza', '¿A dónde huiré de tu presencia?', 2),
  v('proverbios-12-22', 'Proverbios 12:22', 'sabiduria', 'Los que hacen verdad son su deleite', 2),
  v('isaias-55-11', 'Isaías 55:11', 'sabiduria', 'No volverá a mí vacía', 2),
  v('marcos-9-23', 'Marcos 9:23', 'fe-y-valor', 'Al que cree todo le es posible', 2),
  v('efesios-4-2', 'Efesios 4:2', 'amor', 'Con toda humildad y mansedumbre', 2),
  v('salmo-34-18', 'Salmo 34:18', 'esperanza', 'Cercano está el Señor a los quebrantados', 2),
  v('2-corintios-4-18', '2 Corintios 4:18', 'fe-y-valor', 'No mirando las cosas que se ven', 2),
  v('1-juan-5-4', '1 Juan 5:4', 'fe-y-valor', 'Esta es la victoria: nuestra fe', 2),
  v('proverbios-20-22', 'Proverbios 20:22', 'confianza', 'Espera al Señor, y él te salvará', 2),
  v('salmo-107-1', 'Salmo 107:1', 'alabanza', 'Alabad al Señor, porque él es bueno', 2),
  v('romanos-12-10', 'Romanos 12:10', 'amor', 'Amaos con amor fraternal', 2),
  v('galatas-5-1', 'Gálatas 5:1', 'gracia', 'La libertad con que Cristo nos hizo libres', 2),
  v('salmo-119-112', 'Salmo 119:112', 'sabiduria', 'Incliné mi corazón a cumplir tus estatutos', 2),
  v('isaias-40-29', 'Isaías 40:29', 'fe-y-valor', 'Él da esfuerzo al cansado', 2),
  v('1-pedro-1-8', '1 Pedro 1:8', 'alabanza', 'Os alegráis con gozo inefable', 2),
  v('proverbios-14-1', 'Proverbios 14:1', 'sabiduria', 'La mujer sabia edifica su casa', 2),
  v('mateo-18-19', 'Mateo 18:19', 'confianza', 'Si dos de vosotros se pusieren de acuerdo', 2),
  v('salmo-27-4', 'Salmo 27:4', 'alabanza', 'Una cosa he demandado al Señor', 2),
  v('colosenses-3-15', 'Colosenses 3:15', 'esperanza', 'La paz de Dios gobierne en vuestros corazones', 2),
  v('juan-8-36', 'Juan 8:36', 'gracia', 'Seréis verdaderamente libres', 2),
  v('salmo-147-3', 'Salmo 147:3', 'esperanza', 'Él venda sus heridas', 2),
  v('hebreos-4-16', 'Hebreos 4:16', 'gracia', 'Confiadamente al trono de la gracia', 2),
  v('proverbios-10-22', 'Proverbios 10:22', 'alabanza', 'La bendición del Señor es la que enriquece', 2),
  v('mateo-10-31', 'Mateo 10:31', 'identidad', 'Más valéis vosotros que muchos pajarillos', 2),
  v('1-corintios-2-9', '1 Corintios 2:9', 'esperanza', 'Cosas que ojo no vio, ni oído oyó', 2),
  v('salmo-37-7', 'Salmo 37:7', 'confianza', 'Guarda silencio ante el Señor', 2),
  v('romanos-6-23', 'Romanos 6:23', 'gracia', 'La dádiva de Dios es vida eterna', 2),
  v('efesios-6-13', 'Efesios 6:13', 'fe-y-valor', 'Para que podáis resistir en el día malo', 2),
  v('salmo-119-18', 'Salmo 119:18', 'sabiduria', 'Abre mis ojos, y miraré las maravillas', 2),
  v('isaias-26-4', 'Isaías 26:4', 'confianza', 'En el Señor está la fortaleza de los siglos', 2),
  v('1-juan-4-16', '1 Juan 4:16', 'amor', 'El que permanece en amor, permanece en Dios', 2),
  v('proverbios-16-16', 'Proverbios 16:16', 'sabiduria', 'Mejor es adquirir sabiduría que oro preciado', 2),
  v('mateo-6-10', 'Mateo 6:10', 'confianza', 'Hágase tu voluntad', 3),
  v('salmo-91-15', 'Salmo 91:15', 'esperanza', 'Con él estaré yo en la angustia', 3),
  v('2-corintios-9-7', '2 Corintios 9:7', 'amor', 'Dios ama al dador alegre', 3),
  v('filipenses-2-3', 'Filipenses 2:3', 'amor', 'Nada hagáis por contienda o por vanagloria', 3),
  v('salmo-62-5', 'Salmo 62:5', 'esperanza', 'De él es mi esperanza', 3),
  v('juan-1-12', 'Juan 1:12', 'identidad', 'Potestad de ser hechos hijos de Dios', 3),
  v('proverbios-29-25', 'Proverbios 29:25', 'confianza', 'El temor del hombre pondrá lazo', 3),
  v('1-pedro-3-15', '1 Pedro 3:15', 'identidad', 'La esperanza que hay en vosotros', 3),
  v('salmo-119-50', 'Salmo 119:50', 'esperanza', 'Tu dicho me ha vivificado', 3),
  v('romanos-14-8', 'Romanos 14:8', 'identidad', 'Si vivimos, para el Señor vivimos', 3),
  v('hebreos-11-6', 'Hebreos 11:6', 'fe-y-valor', 'Sin fe es imposible agradar a Dios', 3),
  v('salmo-31-24', 'Salmo 31:24', 'esperanza', 'Tome aliento vuestro corazón', 3),
  v('isaias-30-15', 'Isaías 30:15', 'confianza', 'En quietud y en confianza será vuestra fuerza', 3),
  v('proverbios-13-20', 'Proverbios 13:20', 'sabiduria', 'El que anda con sabios, sabio será', 3),
  v('mateo-28-20', 'Mateo 28:20', 'esperanza', 'Yo estoy con vosotros todos los días', 3),
  v('efesios-4-26', 'Efesios 4:26', 'sabiduria', 'No se ponga el sol sobre vuestro enojo', 3),
  v('salmo-119-133', 'Salmo 119:133', 'sabiduria', 'Ordena mis pasos con tu palabra', 3),
  v('1-corintios-13-1', '1 Corintios 13:1', 'amor', 'Si hablase lenguas humanas y angélicas', 3),
  v('juan-14-1', 'Juan 14:1', 'confianza', 'No se turbe vuestro corazón', 3),
  v('proverbios-18-13', 'Proverbios 18:13', 'sabiduria', 'Al que responde palabra antes de oír', 3),
  v('salmo-18-2', 'Salmo 18:2', 'fe-y-valor', 'Roca mía y castillo mío', 3),
  v('romanos-8-1', 'Romanos 8:1', 'gracia', 'Ahora, pues, ninguna condenación hay', 3),
  v('santiago-4-8', 'Santiago 4:8', 'confianza', 'Acercaos a Dios, y él se acercará', 3),
  v('salmo-100-5', 'Salmo 100:5', 'alabanza', 'Su verdad por todas las generaciones', 3),
  v('isaias-43-1', 'Isaías 43:1', 'identidad', 'Te puse nombre, mío eres tú', 3),
  v('1-juan-1-7', '1 Juan 1:7', 'identidad', 'Si andamos en luz, como él está en luz', 3),
  v('proverbios-11-25', 'Proverbios 11:25', 'amor', 'El alma generosa será prosperada', 3),
  v('mateo-11-30', 'Mateo 11:30', 'confianza', 'Mi yugo es fácil, y ligera mi carga', 3),
  v('salmo-119-10', 'Salmo 119:10', 'sabiduria', 'Con todo mi corazón te he buscado', 3),
  v('2-corintios-1-3', '2 Corintios 1:3', 'esperanza', 'Dios de toda consolación', 3),
  v('filipenses-4-8', 'Filipenses 4:8', 'sabiduria', 'Todo lo que es verdadero', 3),
  v('salmo-20-7', 'Salmo 20:7', 'confianza', 'Del Señor nos acordaremos', 3),
  v('juan-15-9', 'Juan 15:9', 'amor', 'Permaneced en mi amor', 3),
  v('proverbios-21-23', 'Proverbios 21:23', 'sabiduria', 'Su alma guarda de angustias', 3),
  v('1-pedro-5-6', '1 Pedro 5:6', 'identidad', 'Bajo la poderosa mano de Dios', 3),
  v('salmo-121-5', 'Salmo 121:5', 'esperanza', 'El Señor es tu guardador', 3),
  v('romanos-12-9', 'Romanos 12:9', 'amor', 'El amor sea sin fingimiento', 3),
  v('hebreos-10-23', 'Hebreos 10:23', 'esperanza', 'Mantengamos firme, sin fluctuar', 3),
  v('salmo-56-3', 'Salmo 56:3', 'confianza', 'En el día que temo, yo en ti confío', 3),
  v('isaias-40-8', 'Isaías 40:8', 'esperanza', 'Sécase la hierba, marchítase la flor', 3),
  v('1-juan-4-18', '1 Juan 4:18', 'amor', 'El perfecto amor echa fuera el temor', 3),
  v('proverbios-15-13', 'Proverbios 15:13', 'alabanza', 'El corazón alegre hermosea el rostro', 3),
  v('mateo-7-8', 'Mateo 7:8', 'confianza', 'El que busca, halla', 3),
  v('salmo-33-12', 'Salmo 33:12', 'alabanza', 'La nación cuyo Dios es el Señor', 3),
  v('2-timoteo-3-16', '2 Timoteo 3:16', 'sabiduria', 'Toda la Escritura es inspirada por Dios', 3),
  v('josue-24-15', 'Josué 24:15', 'identidad', 'Yo y mi casa serviremos al Señor', 3),
  v('salmo-119-103', 'Salmo 119:103', 'alabanza', '¡Cuán dulces son a mi paladar tus palabras!', 3),
  v('santiago-1-2', 'Santiago 1:2', 'alabanza', 'Tened por sumo gozo', 3),
  v('proverbios-16-32', 'Proverbios 16:32', 'sabiduria', 'Mejor es el que tarda en airarse', 3),
  v('salmo-119-116', 'Salmo 119:116', 'esperanza', 'Susténtame conforme a tu palabra y viviré', 3),
  v('mateo-5-6', 'Mateo 5:6', 'gracia', 'Hambre y sed de justicia', 3),
  v('proverbios-10-12', 'Proverbios 10:12', 'amor', 'El amor cubrirá todas las faltas', 3),
  v('salmo-145-18', 'Salmo 145:18', 'confianza', 'A todos los que le invocan en verdad', 3),
  v('galatas-6-2', 'Gálatas 6:2', 'amor', 'Sobrellevad los unos las cargas de los otros', 3),
  v('2-corintios-5-21', '2 Corintios 5:21', 'gracia', 'Hechos justicia de Dios en él', 3),
  v('salmo-27-14', 'Salmo 27:14', 'esperanza', 'Aguarda al Señor; esfuérzate', 3),
  v('mateo-6-20', 'Mateo 6:20', 'sabiduria', 'Haceos tesoros en el cielo', 3),
  v('proverbios-24-16', 'Proverbios 24:16', 'fe-y-valor', 'Cae el justo, y vuelve a levantarse', 3),
  v('juan-14-15', 'Juan 14:15', 'amor', 'Si me amáis, guardad mis mandamientos', 3),
  v('isaias-40-28', 'Isaías 40:28', 'fe-y-valor', 'No desfallece, ni se fatiga', 3),
  v('salmo-32-8', 'Salmo 32:8', 'sabiduria', 'Te enseñaré el camino en que debes andar', 3),
  v('romanos-8-37', 'Romanos 8:37', 'fe-y-valor', 'Más que vencedores', 3),
  v('1-juan-3-18', '1 Juan 3:18', 'amor', 'No amemos de palabra ni de lengua', 3),
  v('filipenses-2-5', 'Filipenses 2:5', 'identidad', 'Haya en vosotros este sentir', 3),
  v('mateo-18-22', 'Mateo 18:22', 'gracia', 'Hasta setenta veces siete', 3),
  v('proverbios-16-7', 'Proverbios 16:7', 'sabiduria', 'Aun a sus enemigos hace estar en paz con él', 3),
  v('salmo-62-8', 'Salmo 62:8', 'confianza', 'Derramad delante de él vuestro corazón', 3),
  v('2-timoteo-2-15', '2 Timoteo 2:15', 'identidad', 'Obrero que no tiene de qué avergonzarse', 3),
  v('juan-10-28', 'Juan 10:28', 'gracia', 'Nadie las arrebatará de mi mano', 3),
  v('hebreos-12-2', 'Hebreos 12:2', 'fe-y-valor', 'Puestos los ojos en Jesús', 3),
  v('salmo-119-165', 'Salmo 119:165', 'sabiduria', 'Mucha paz tienen los que aman tu ley', 3),
  v('isaias-54-10', 'Isaías 54:10', 'amor', 'No se apartará de ti mi misericordia', 3),
  v('efesios-2-19', 'Efesios 2:19', 'identidad', 'Miembros de la familia de Dios', 3),
  v('proverbios-17-22', 'Proverbios 17:22', 'alabanza', 'El corazón alegre es buena medicina', 3),
  v('romanos-8-14', 'Romanos 8:14', 'identidad', 'Guiados por el Espíritu de Dios', 3),
  v('1-pedro-2-24', '1 Pedro 2:24', 'gracia', 'Él mismo llevó nuestros pecados', 3),
  v('salmo-37-3', 'Salmo 37:3', 'confianza', 'Confía en el Señor, y haz el bien', 3),
  v('proverbios-18-21', 'Proverbios 18:21', 'sabiduria', 'La muerte y la vida, en poder de la lengua', 3),
  v('isaias-41-13', 'Isaías 41:13', 'fe-y-valor', 'Quien te sostiene de tu mano derecha', 3),
  v('salmo-90-12', 'Salmo 90:12', 'sabiduria', 'Enséñanos a contar nuestros días', 3),
  v('santiago-1-12', 'Santiago 1:12', 'fe-y-valor', 'Recibirá la corona de vida', 3),
  v('1-juan-2-17', '1 Juan 2:17', 'esperanza', 'El mundo pasa, y sus deseos', 3),
  v('filipenses-4-11', 'Filipenses 4:11', 'confianza', 'He aprendido a contentarme', 3),
  v('salmo-34-10', 'Salmo 34:10', 'confianza', 'Los que buscan al Señor no tendrán falta', 3),
  v('mateo-25-40', 'Mateo 25:40', 'amor', 'A mí lo hicisteis', 3),
  v('colosenses-3-12', 'Colosenses 3:12', 'identidad', 'Escogidos de Dios, santos y amados', 3),
  v('salmo-119-71', 'Salmo 119:71', 'sabiduria', 'Bueno me es haber sido humillado', 3),
  v('proverbios-22-1', 'Proverbios 22:1', 'sabiduria', 'La buena fama más que la plata y el oro', 3),
  v('juan-12-46', 'Juan 12:46', 'identidad', 'Yo, la luz, he venido al mundo', 3),
  v('romanos-12-1', 'Romanos 12:1', 'identidad', 'Sacrificio vivo, santo, agradable a Dios', 3),
  v('2-corintios-5-1', '2 Corintios 5:1', 'esperanza', 'Tenemos de Dios un edificio', 3),
  v('salmo-103-1', 'Salmo 103:1', 'alabanza', 'Bendiga todo mi ser su santo nombre', 3),
  v('isaias-9-6', 'Isaías 9:6', 'alabanza', 'Admirable, Consejero, Dios Fuerte', 3),
  v('1-corintios-1-18', '1 Corintios 1:18', 'gracia', 'La palabra de la cruz', 3),
  v('salmo-119-37', 'Salmo 119:37', 'sabiduria', 'Aparta mis ojos, que no vean la vanidad', 3),
  v('proverbios-29-11', 'Proverbios 29:11', 'sabiduria', 'El sabio al fin la sosiega', 3),
  v('mateo-5-4', 'Mateo 5:4', 'esperanza', 'Ellos recibirán consolación', 3),
  v('galatas-5-13', 'Gálatas 5:13', 'identidad', 'A libertad fuisteis llamados', 3),
  v('salmo-8-1', 'Salmo 8:1', 'alabanza', '¡Cuán grande es tu nombre en toda la tierra!', 3),
  v('filipenses-1-21', 'Filipenses 1:21', 'identidad', 'Para mí el vivir es Cristo', 3),
  v('1-pedro-5-8', '1 Pedro 5:8', 'fe-y-valor', 'Sed sobrios, y velad', 4),
  v('salmo-121-1', 'Salmo 121:1', 'esperanza', 'Alzaré mis ojos a los montes', 4),
  v('proverbios-15-22', 'Proverbios 15:22', 'sabiduria', 'En la multitud de consejeros se afirman', 4),
  v('juan-13-35', 'Juan 13:35', 'identidad', 'Conocerán todos que sois mis discípulos', 4),
  v('romanos-5-1', 'Romanos 5:1', 'gracia', 'Tenemos paz para con Dios', 4),
  v('hebreos-13-5', 'Hebreos 13:5', 'confianza', 'No te desampararé, ni te dejaré', 4),
  v('salmo-119-14', 'Salmo 119:14', 'alabanza', 'Me he gozado en el camino de tus testimonios', 4),
  v('isaias-40-26', 'Isaías 40:26', 'alabanza', 'Levantad en alto vuestros ojos', 4),
  v('efesios-4-31', 'Efesios 4:31', 'amor', 'Quítense de vosotros toda amargura', 4),
  v('salmo-40-1', 'Salmo 40:1', 'esperanza', 'Pacientemente esperé al Señor', 4),
  v('1-juan-2-15', '1 Juan 2:15', 'identidad', 'No améis al mundo', 4),
  v('proverbios-20-1', 'Proverbios 20:1', 'sabiduria', 'El vino es escarnecedor', 4),
  v('mateo-22-37', 'Mateo 22:37', 'amor', 'Con toda tu alma, y con toda tu mente', 4),
  v('2-corintios-12-10', '2 Corintios 12:10', 'fe-y-valor', 'Cuando soy débil, entonces soy fuerte', 4),
  v('colosenses-4-2', 'Colosenses 4:2', 'alabanza', 'Perseverad en la oración', 4),
  v('salmo-51-1', 'Salmo 51:1', 'gracia', 'Ten piedad de mí, oh Dios', 4),
  v('juan-6-47', 'Juan 6:47', 'gracia', 'El que cree en mí, tiene vida eterna', 4),
  v('proverbios-16-8', 'Proverbios 16:8', 'sabiduria', 'Mejor es lo poco con justicia', 4),
  v('1-corintios-10-31', '1 Corintios 10:31', 'alabanza', 'Hacedlo todo para la gloria de Dios', 4),
  v('isaias-26-12', 'Isaías 26:12', 'esperanza', 'Señor, tú nos darás paz', 4),
  v('efesios-5-15', 'Efesios 5:15', 'sabiduria', 'No como necios sino como sabios', 4),
  v('santiago-1-19', 'Santiago 1:19', 'sabiduria', 'Pronto para oír, tardo para hablar', 4),
  v('1-pedro-1-15', '1 Pedro 1:15', 'identidad', 'Sed también vosotros santos', 4),
  v('proverbios-14-29', 'Proverbios 14:29', 'sabiduria', 'Grande de entendimiento', 4),
  v('mateo-6-12', 'Mateo 6:12', 'gracia', 'Perdónanos nuestras deudas', 4),
  v('salmo-119-72', 'Salmo 119:72', 'sabiduria', 'Mejor me es la ley de tu boca', 4),
  v('romanos-15-7', 'Romanos 15:7', 'amor', 'Recibíos los unos a los otros', 4),
  v('filipenses-2-14', 'Filipenses 2:14', 'sabiduria', 'Haced todo sin murmuraciones', 4),
  v('salmo-118-14', 'Salmo 118:14', 'alabanza', 'Mi fortaleza y mi canción es el Señor', 4),
  v('juan-15-4', 'Juan 15:4', 'identidad', 'Permaneced en mí, y yo en vosotros', 4),
  v('proverbios-12-15', 'Proverbios 12:15', 'sabiduria', 'El que obedece al consejo es sabio', 4),
  v('2-corintios-4-7', '2 Corintios 4:7', 'identidad', 'Este tesoro en vasos de barro', 4),
  v('isaias-53-6', 'Isaías 53:6', 'gracia', 'Todos nosotros nos descarriamos como ovejas', 4),
  v('salmo-95-1', 'Salmo 95:1', 'alabanza', 'Venid, aclamemos alegremente al Señor', 4),
  v('1-juan-5-13', '1 Juan 5:13', 'gracia', 'Para que sepáis que tenéis vida eterna', 4),
  v('proverbios-13-3', 'Proverbios 13:3', 'sabiduria', 'El que guarda su boca guarda su alma', 4),
  v('mateo-18-3', 'Mateo 18:3', 'identidad', 'Si no os volvéis y os hacéis como niños', 4),
  v('salmo-119-45', 'Salmo 119:45', 'sabiduria', 'Andaré en libertad', 4),
  v('romanos-8-2', 'Romanos 8:2', 'gracia', 'La ley del Espíritu de vida', 4),
  v('efesios-6-1', 'Efesios 6:1', 'sabiduria', 'Hijos, obedeced en el Señor a vuestros padres', 4),
  v('salmo-19-1', 'Salmo 19:1', 'alabanza', 'Los cielos cuentan la gloria de Dios', 4),
  v('juan-4-24', 'Juan 4:24', 'alabanza', 'En espíritu y en verdad', 4),
  v('proverbios-11-2', 'Proverbios 11:2', 'sabiduria', 'Con los humildes está la sabiduría', 4),
  v('1-corintios-15-58', '1 Corintios 15:58', 'fe-y-valor', 'Vuestro trabajo en el Señor no es en vano', 4),
  v('santiago-4-10', 'Santiago 4:10', 'identidad', 'Humillaos delante del Señor, y él os exaltará', 4),
  v('salmo-119-28', 'Salmo 119:28', 'esperanza', 'Se deshace mi alma de ansiedad', 4),
  v('proverbios-15-28', 'Proverbios 15:28', 'sabiduria', 'El corazón del justo piensa para responder', 4),
  v('colosenses-3-16', 'Colosenses 3:16', 'sabiduria', 'La palabra de Cristo more en abundancia', 4),
  v('2-corintios-3-18', '2 Corintios 3:18', 'identidad', 'Transformados de gloria en gloria', 4),
  v('juan-1-14', 'Juan 1:14', 'identidad', 'Y aquel Verbo fue hecho carne', 4),
  v('proverbios-21-3', 'Proverbios 21:3', 'sabiduria', 'Hacer justicia y juicio', 4),
  v('romanos-12-18', 'Romanos 12:18', 'amor', 'Estad en paz con todos los hombres', 4),
  v('filipenses-3-13', 'Filipenses 3:13', 'fe-y-valor', 'Olvidando lo que queda atrás', 4),
  v('salmo-119-77', 'Salmo 119:77', 'alabanza', 'Tu ley es mi delicia', 4),
  v('isaias-43-19', 'Isaías 43:19', 'esperanza', 'He aquí que yo hago cosa nueva', 4),
  v('efesios-4-15', 'Efesios 4:15', 'amor', 'Siguiendo la verdad en amor', 4),
  v('salmo-37-24', 'Salmo 37:24', 'confianza', 'El Señor sostiene su mano', 4),
  v('proverbios-28-13', 'Proverbios 28:13', 'gracia', 'El que confiesa alcanzará misericordia', 4),
  v('mateo-5-11', 'Mateo 5:11', 'fe-y-valor', 'Cuando por mi causa os vituperen', 4),
  v('2-corintios-9-8', '2 Corintios 9:8', 'gracia', 'Que abunde en vosotros toda gracia', 4),
  v('hebreos-11-3', 'Hebreos 11:3', 'fe-y-valor', 'Por la fe entendemos', 4),
  v('salmo-86-15', 'Salmo 86:15', 'gracia', 'Dios misericordioso y clemente', 4),
  v('proverbios-16-20', 'Proverbios 16:20', 'sabiduria', 'El entendido en la palabra hallará el bien', 4),
  v('isaias-55-6', 'Isaías 55:6', 'gracia', 'Buscad al Señor mientras puede ser hallado', 4),
  v('galatas-6-7', 'Gálatas 6:7', 'sabiduria', 'Lo que el hombre sembrare, eso también segará', 4),
  v('colosenses-1-13', 'Colosenses 1:13', 'gracia', 'Trasladado al reino de su amado Hijo', 4),
  v('salmo-100-3', 'Salmo 100:3', 'alabanza', 'Pueblo suyo somos, y ovejas de su prado', 4),
  v('proverbios-3-6', 'Proverbios 3:6', 'confianza', 'Él enderezará tus veredas', 4),
  v('salmo-119-107', 'Salmo 119:107', 'esperanza', 'Afligido estoy en gran manera', 4),
  v('mateo-6-26', 'Mateo 6:26', 'confianza', 'Mirad las aves del cielo', 4),
  v('proverbios-15-4', 'Proverbios 15:4', 'sabiduria', 'La lengua apacible es árbol de vida', 4),
  v('1-corintios-12-12', '1 Corintios 12:12', 'identidad', 'Así como el cuerpo es uno', 4),
  v('salmo-119-147', 'Salmo 119:147', 'alabanza', 'Se anticiparon mis ojos a las vigilias', 4),
  v('galatas-3-28', 'Gálatas 3:28', 'identidad', 'Todos vosotros sois uno en Cristo Jesús', 4),
  v('2-corintios-4-16', '2 Corintios 4:16', 'esperanza', 'Por tanto, no desmayamos', 4),
  v('salmo-28-7', 'Salmo 28:7', 'confianza', 'En él confió mi corazón, y fui ayudado', 4),
  v('mateo-5-12', 'Mateo 5:12', 'alabanza', 'Vuestro galardón es grande en los cielos', 4),
  v('proverbios-19-11', 'Proverbios 19:11', 'sabiduria', 'Su honra es pasar por alto la ofensa', 4),
  v('juan-15-8', 'Juan 15:8', 'identidad', 'Que llevéis mucho fruto', 4),
  v('salmo-33-4', 'Salmo 33:4', 'alabanza', 'Recta es la palabra del Señor', 4),
  v('romanos-12-15', 'Romanos 12:15', 'amor', 'Gozaos con los que se gozan', 4),
  v('1-juan-4-10', '1 Juan 4:10', 'amor', 'En esto consiste el amor', 4),
  v('mateo-7-1', 'Mateo 7:1', 'amor', 'No juzguéis, para que no seáis juzgados', 4),
  v('proverbios-16-31', 'Proverbios 16:31', 'sabiduria', 'Corona de honra es la cabeza cana', 4),
  v('salmo-63-3', 'Salmo 63:3', 'alabanza', 'Mejor es tu misericordia que la vida', 4),
  v('2-timoteo-2-13', '2 Timoteo 2:13', 'confianza', 'Él permanece fiel', 4),
  v('juan-10-9', 'Juan 10:9', 'gracia', 'Yo soy la puerta', 4),
  v('hebreos-12-14', 'Hebreos 12:14', 'identidad', 'La santidad, sin la cual nadie verá al Señor', 4),
  v('salmo-119-82', 'Salmo 119:82', 'esperanza', '¿Cuándo me consolarás?', 4),
  v('1-corintios-1-30', '1 Corintios 1:30', 'gracia', 'Sabiduría, justificación y santificación', 4),
  v('isaias-53-4', 'Isaías 53:4', 'gracia', 'Ciertamente llevó él nuestras enfermedades', 4),
  v('efesios-3-17', 'Efesios 3:17', 'amor', 'Arraigados y cimentados en amor', 4),
  v('salmo-119-174', 'Salmo 119:174', 'alabanza', 'He deseado tu salvación, oh Señor', 4),
  v('proverbios-20-27', 'Proverbios 20:27', 'sabiduria', 'Lámpara del Señor es el espíritu del hombre', 4),
  v('romanos-8-38', 'Romanos 8:38', 'amor', 'Ni la muerte, ni la vida', 4),
  v('1-pedro-3-9', '1 Pedro 3:9', 'amor', 'No devolviendo mal por mal', 4),
  v('salmo-37-8', 'Salmo 37:8', 'sabiduria', 'Deja la ira, y desecha el enojo', 4),
  v('lucas-6-38', 'Lucas 6:38', 'amor', 'Medida buena, apretada, remecida y rebosando', 4),
  v('proverbios-24-10', 'Proverbios 24:10', 'fe-y-valor', 'Si fueres flojo en el día de trabajo', 4),
  v('salmo-103-12', 'Salmo 103:12', 'gracia', 'Cuanto está lejos el oriente del occidente', 4),
  v('santiago-1-27', 'Santiago 1:27', 'amor', 'La religión pura y sin mácula', 5),
  v('1-juan-3-2', '1 Juan 3:2', 'identidad', 'Ahora somos hijos de Dios', 5),
  v('filipenses-2-13', 'Filipenses 2:13', 'confianza', 'Así el querer como el hacer', 5),
  v('salmo-34-7', 'Salmo 34:7', 'esperanza', 'El ángel del Señor acampa alrededor', 5),
  v('mateo-24-13', 'Mateo 24:13', 'fe-y-valor', 'El que persevere hasta el fin', 5),
  v('colosenses-2-6', 'Colosenses 2:6', 'identidad', 'Andad en él', 5),
  v('salmo-119-151', 'Salmo 119:151', 'confianza', 'Cercano estás tú, oh Señor', 5),
  v('proverbios-17-9', 'Proverbios 17:9', 'amor', 'El que cubre la falta busca amistad', 5),
  v('romanos-12-16', 'Romanos 12:16', 'amor', 'Asociándoos con los humildes', 5),
  v('salmo-103-13', 'Salmo 103:13', 'amor', 'Como el padre se compadece de los hijos', 5),
  v('1-corintios-3-16', '1 Corintios 3:16', 'identidad', 'Sois templo de Dios', 5),
  v('salmo-119-16', 'Salmo 119:16', 'sabiduria', 'No me olvidaré de tus palabras', 5),
  v('proverbios-27-1', 'Proverbios 27:1', 'sabiduria', 'No sabes qué dará de sí el día', 5),
  v('mateo-5-16', 'Mateo 5:16', 'identidad', 'Así alumbre vuestra luz', 5),
  v('galatas-6-10', 'Gálatas 6:10', 'amor', 'Hagamos bien a todos', 5),
  v('salmo-9-1', 'Salmo 9:1', 'alabanza', 'Contaré todas tus maravillas', 5),
  v('filipenses-4-7', 'Filipenses 4:7', 'esperanza', 'Que sobrepasa todo entendimiento', 5),
  v('1-pedro-4-10', '1 Pedro 4:10', 'identidad', 'Cada uno según el don que ha recibido', 5),
  v('salmo-126-5', 'Salmo 126:5', 'esperanza', 'Los que sembraron con lágrimas', 5),
  v('lucas-16-10', 'Lucas 16:10', 'sabiduria', 'El que es fiel en lo muy poco', 5),
  v('proverbios-16-2', 'Proverbios 16:2', 'sabiduria', 'El Señor pesa los espíritus', 5),
  v('romanos-6-14', 'Romanos 6:14', 'gracia', 'No estáis bajo la ley, sino bajo la gracia', 5),
  v('hebreos-10-24', 'Hebreos 10:24', 'amor', 'Estimularnos al amor y a las buenas obras', 5),
  v('salmo-119-176', 'Salmo 119:176', 'gracia', 'Anduve errante como oveja perdida', 5),
  v('proverbios-12-18', 'Proverbios 12:18', 'sabiduria', 'La lengua de los sabios es medicina', 5),
  v('salmo-119-111', 'Salmo 119:111', 'alabanza', 'Son el gozo de mi corazón', 5),
  v('2-corintios-1-4', '2 Corintios 1:4', 'esperanza', 'Nos consuela en todas nuestras tribulaciones', 5),
  v('colosenses-3-14', 'Colosenses 3:14', 'amor', 'Vestíos de amor, que es el vínculo perfecto', 5),
  v('proverbios-19-17', 'Proverbios 19:17', 'amor', 'A prestar al Señor da el que da al pobre', 5),
  v('salmo-119-9', 'Salmo 119:9', 'sabiduria', '¿Con qué limpiará el joven su camino?', 5),
  v('isaias-32-17', 'Isaías 32:17', 'esperanza', 'El efecto de la justicia será paz', 5),
  v('1-pedro-1-22', '1 Pedro 1:22', 'amor', 'Amaos entrañablemente, de corazón puro', 5),
  v('proverbios-15-30', 'Proverbios 15:30', 'alabanza', 'La luz de los ojos alegra el corazón', 5),
  v('salmo-119-7', 'Salmo 119:7', 'alabanza', 'Te alabaré con rectitud de corazón', 5),
  v('proverbios-23-23', 'Proverbios 23:23', 'sabiduria', 'Compra la verdad, y no la vendas', 5),
  v('salmo-119-162', 'Salmo 119:162', 'alabanza', 'Como el que halla muchos despojos', 5),
  v('proverbios-14-12', 'Proverbios 14:12', 'sabiduria', 'Hay camino que al hombre le parece derecho', 5),
  v('salmo-119-33', 'Salmo 119:33', 'sabiduria', 'Enséñame, oh Señor, el camino', 5),
  v('isaias-55-8', 'Isaías 55:8', 'confianza', 'Mis pensamientos no son vuestros pensamientos', 5),
  v('efesios-6-11', 'Efesios 6:11', 'fe-y-valor', 'Vestíos de toda la armadura de Dios', 5),
  v('salmo-119-127', 'Salmo 119:127', 'sabiduria', 'He amado tus mandamientos más que el oro', 5),
  v('salmo-119-98', 'Salmo 119:98', 'sabiduria', 'Me has hecho más sabio que mis enemigos', 5),
  v('salmo-119-175', 'Salmo 119:175', 'alabanza', 'Viva mi alma y te alabe', 5),
  v('mateo-5-10', 'Mateo 5:10', 'fe-y-valor', 'Padecen persecución por causa de la justicia', 5),
  v('lamentaciones-3-22-23', 'Lamentaciones 3:22-23', 'esperanza', 'Nuevas son cada mañana', 5),
  v('salmo-55-22', 'Salmo 55:22', 'confianza', 'Echa sobre el Señor tu carga', 5),
  v('juan-13-34-35', 'Juan 13:34-35', 'amor', 'Que os améis unos a otros', 5),
  v('jeremias-1-5', 'Jeremías 1:5', 'identidad', 'Antes que te formase en el vientre te conocí', 5),
  v('salmo-139-13', 'Salmo 139:13', 'identidad', 'Tú me hiciste en el vientre de mi madre', 5),
  v('genesis-1-27', 'Génesis 1:27', 'identidad', 'A imagen de Dios lo creó', 5),
  v('1-samuel-16-7', '1 Samuel 16:7', 'identidad', 'El Señor mira el corazón', 5),
  v('sofonias-3-17', 'Sofonías 3:17', 'amor', 'Se regocijará sobre ti con cánticos', 5),
  v('cantares-8-7', 'Cantares 8:7', 'amor', 'Las muchas aguas no podrán apagar el amor', 5),
  v('eclesiastes-4-12', 'Eclesiastés 4:12', 'amor', 'Cordón de tres dobleces no se rompe pronto', 5),
  v('genesis-2-24', 'Génesis 2:24', 'amor', 'Serán una sola carne', 5),
  v('mateo-19-6', 'Mateo 19:6', 'amor', 'Lo que Dios juntó, no lo separe el hombre', 5),
  v('rut-1-16', 'Rut 1:16', 'amor', 'Tu pueblo será mi pueblo, y tu Dios mi Dios', 5),
  v('cantares-6-3', 'Cantares 6:3', 'amor', 'Yo soy de mi amado, y mi amado es mío', 5),
  v('cantares-8-6', 'Cantares 8:6', 'amor', 'Fuerte es como la muerte el amor', 5),
  v('eclesiastes-3-1', 'Eclesiastés 3:1', 'sabiduria', 'Todo tiene su tiempo', 5),
  v('eclesiastes-3-11', 'Eclesiastés 3:11', 'alabanza', 'Todo lo hizo hermoso en su tiempo', 5),
  v('apocalipsis-21-5', 'Apocalipsis 21:5', 'esperanza', 'Yo hago nuevas todas las cosas', 5),
  v('nahum-1-7', 'Nahúm 1:7', 'confianza', 'Fortaleza en el día de la angustia', 5),
  v('exodo-14-14', 'Éxodo 14:14', 'confianza', 'El Señor peleará por vosotros', 5),
  v('mateo-5-7', 'Mateo 5:7', 'gracia', 'Bienaventurados los misericordiosos', 5),
  v('mateo-5-13', 'Mateo 5:13', 'identidad', 'Sois la sal de la tierra', 5),
  v('juan-10-11', 'Juan 10:11', 'identidad', 'Yo soy el buen pastor', 5),
  v('juan-8-58', 'Juan 8:58', 'identidad', 'Antes que Abraham fuese, yo soy', 5),
  v('apocalipsis-1-8', 'Apocalipsis 1:8', 'identidad', 'Yo soy el Alfa y la Omega', 5),
  v('juan-1-5', 'Juan 1:5', 'esperanza', 'La luz en las tinieblas resplandece', 5),
  v('salmo-34-1', 'Salmo 34:1', 'alabanza', 'Bendeciré al Señor en todo tiempo', 5),
  v('salmo-61-2', 'Salmo 61:2', 'esperanza', 'Llévame a la roca que es más alta que yo', 5),
  v('salmo-73-26', 'Salmo 73:26', 'esperanza', 'Mi porción es Dios para siempre', 5),
  v('salmo-84-10', 'Salmo 84:10', 'alabanza', 'Mejor es un día en tus atrios que mil', 5),
  v('salmo-127-1', 'Salmo 127:1', 'sabiduria', 'Si el Señor no edificare la casa', 5),
  v('salmo-127-3', 'Salmo 127:3', 'amor', 'Herencia del Señor son los hijos', 5),
  v('salmo-150-6', 'Salmo 150:6', 'alabanza', 'Todo lo que respira alabe al Señor', 5),
  v('salmo-4-8', 'Salmo 4:8', 'confianza', 'En paz me acostaré, y asimismo dormiré', 5),
  v('salmo-3-3', 'Salmo 3:3', 'fe-y-valor', 'Tú, oh Señor, eres escudo alrededor de mí', 5),
  v('salmo-51-12', 'Salmo 51:12', 'gracia', 'Vuélveme el gozo de tu salvación', 5),
  v('salmo-51-7', 'Salmo 51:7', 'gracia', 'Lávame, y seré más blanco que la nieve', 5),
  v('salmo-100-4', 'Salmo 100:4', 'alabanza', 'Entrad por sus puertas con acción de gracias', 5),
  v('salmo-126-3', 'Salmo 126:3', 'alabanza', 'Grandes cosas ha hecho el Señor con nosotros', 5),
  v('salmo-133-1', 'Salmo 133:1', 'amor', 'Habitar los hermanos juntos en armonía', 5),
  v('salmo-23-5', 'Salmo 23:5', 'alabanza', 'Mi copa está rebosando', 5),
  v('salmo-42-11', 'Salmo 42:11', 'esperanza', 'Espera en Dios, porque aún he de alabarle', 5),
  v('salmo-46-5', 'Salmo 46:5', 'fe-y-valor', 'Dios está en medio de ella', 5),
  v('salmo-31-15', 'Salmo 31:15', 'confianza', 'En tu mano están mis tiempos', 5),
  v('salmo-20-4', 'Salmo 20:4', 'esperanza', 'Te dé conforme al deseo de tu corazón', 5),
  v('salmo-27-10', 'Salmo 27:10', 'amor', 'Aunque mi padre y mi madre me dejaran', 5),
  v('salmo-30-11', 'Salmo 30:11', 'alabanza', 'Has cambiado mi lamento en baile', 5),
  v('salmo-112-7', 'Salmo 112:7', 'confianza', 'No tendrá temor de malas noticias', 5),
  v('proverbios-31-10', 'Proverbios 31:10', 'amor', 'Mujer virtuosa, ¿quién la hallará?', 5),
  v('proverbios-18-22', 'Proverbios 18:22', 'amor', 'El que halla esposa halla el bien', 5),
  v('proverbios-1-7', 'Proverbios 1:7', 'sabiduria', 'El principio de la sabiduría', 5),
  v('proverbios-2-6', 'Proverbios 2:6', 'sabiduria', 'El Señor da la sabiduría', 5),
  v('proverbios-4-18', 'Proverbios 4:18', 'esperanza', 'Como la luz de la aurora', 5),
  v('proverbios-3-24', 'Proverbios 3:24', 'confianza', 'Te acostarás, y tu sueño será grato', 5),
  v('eclesiastes-4-9', 'Eclesiastés 4:9', 'amor', 'Mejores son dos que uno', 5),
  v('eclesiastes-12-1', 'Eclesiastés 12:1', 'sabiduria', 'Acuérdate de tu Creador', 5),
  v('isaias-30-21', 'Isaías 30:21', 'sabiduria', 'Este es el camino, andad por él', 6),
  v('isaias-40-11', 'Isaías 40:11', 'amor', 'Como pastor apacentará su rebaño', 6),
  v('isaias-43-4', 'Isaías 43:4', 'amor', 'Porque a mis ojos fuiste de gran estima', 6),
  v('isaias-49-16', 'Isaías 49:16', 'amor', 'En las palmas de las manos te tengo esculpida', 6),
  v('isaias-58-11', 'Isaías 58:11', 'esperanza', 'Serás como huerto de riego', 6),
  v('isaias-60-1', 'Isaías 60:1', 'identidad', 'Levántate, resplandece', 6),
  v('isaias-61-3', 'Isaías 61:3', 'esperanza', 'Óleo de gozo en lugar de luto', 6),
  v('isaias-64-8', 'Isaías 64:8', 'identidad', 'Nosotros barro, y tú el que nos formaste', 6),
  v('isaias-6-8', 'Isaías 6:8', 'identidad', 'Heme aquí, envíame a mí', 6),
  v('isaias-1-18', 'Isaías 1:18', 'gracia', 'Como la nieve serán emblanquecidos', 6),
  v('isaias-46-4', 'Isaías 46:4', 'esperanza', 'Hasta las canas os soportaré', 6),
  v('isaias-66-13', 'Isaías 66:13', 'amor', 'Como aquel a quien consuela su madre', 6),
  v('jeremias-29-13', 'Jeremías 29:13', 'confianza', 'Me buscaréis y me hallaréis', 6),
  v('jeremias-17-14', 'Jeremías 17:14', 'gracia', 'Sáname, oh Señor, y seré sano', 6),
  v('jeremias-30-17', 'Jeremías 30:17', 'esperanza', 'Yo haré venir sanidad para ti', 6),
  v('jeremias-32-27', 'Jeremías 32:27', 'fe-y-valor', '¿Habrá algo que sea difícil para mí?', 6),
  v('ezequiel-36-26', 'Ezequiel 36:26', 'gracia', 'Os daré corazón nuevo', 6),
  v('miqueas-6-8', 'Miqueas 6:8', 'sabiduria', 'Hacer justicia, amar misericordia', 6),
  v('miqueas-7-8', 'Miqueas 7:8', 'esperanza', 'Aunque caí, me levantaré', 6),
  v('habacuc-3-17-18', 'Habacuc 3:17-18', 'alabanza', 'Con todo, yo me alegraré en el Señor', 6),
  v('joel-2-25', 'Joel 2:25', 'esperanza', 'Os restituiré los años que comió la oruga', 6),
  v('zacarias-4-6', 'Zacarías 4:6', 'fe-y-valor', 'No con ejército, ni con fuerza', 6),
  v('nehemias-8-10', 'Nehemías 8:10', 'alabanza', 'El gozo del Señor es vuestra fuerza', 6),
  v('ester-4-14', 'Ester 4:14', 'identidad', 'Para esta hora has llegado al reino', 6),
  v('job-19-25', 'Job 19:25', 'esperanza', 'Yo sé que mi Redentor vive', 6),
  v('job-42-2', 'Job 42:2', 'confianza', 'Yo conozco que todo lo puedes', 6),
  v('job-1-21', 'Job 1:21', 'confianza', 'El Señor dio, y el Señor quitó', 6),
  v('genesis-28-15', 'Génesis 28:15', 'confianza', 'Yo estoy contigo, y te guardaré', 6),
  v('genesis-50-20', 'Génesis 50:20', 'confianza', 'Dios lo encaminó a bien', 6),
  v('genesis-22-14', 'Génesis 22:14', 'confianza', 'El Señor proveerá', 6),
  v('genesis-12-2', 'Génesis 12:2', 'alabanza', 'Te bendeciré, y serás bendición', 6),
  v('genesis-16-13', 'Génesis 16:13', 'identidad', 'Tú eres Dios que ve', 6),
  v('genesis-2-18', 'Génesis 2:18', 'amor', 'No es bueno que el hombre esté solo', 6),
  v('exodo-15-26', 'Éxodo 15:26', 'gracia', 'Yo soy el Señor tu sanador', 6),
  v('exodo-33-14', 'Éxodo 33:14', 'confianza', 'Mi presencia irá contigo, y te daré descanso', 6),
  v('exodo-20-12', 'Éxodo 20:12', 'amor', 'Honra a tu padre y a tu madre', 6),
  v('exodo-3-14', 'Éxodo 3:14', 'identidad', 'Yo soy el que soy', 6),
  v('numeros-23-19', 'Números 23:19', 'confianza', 'Dios no es hombre, para que mienta', 6),
  v('deuteronomio-33-27', 'Deuteronomio 33:27', 'confianza', 'El eterno Dios es tu refugio', 6),
  v('deuteronomio-30-19', 'Deuteronomio 30:19', 'sabiduria', 'Escoge, pues, la vida', 6),
  v('josue-1-8', 'Josué 1:8', 'sabiduria', 'De día y de noche meditarás en él', 6),
  v('1-samuel-3-10', '1 Samuel 3:10', 'identidad', 'Habla, porque tu siervo oye', 6),
  v('1-samuel-1-27', '1 Samuel 1:27', 'alabanza', 'Por este niño oraba', 6),
  v('1-samuel-7-12', '1 Samuel 7:12', 'alabanza', 'Hasta aquí nos ayudó el Señor', 6),
  v('1-reyes-19-12', '1 Reyes 19:12', 'confianza', 'Un silbo apacible y delicado', 6),
  v('2-cronicas-7-14', '2 Crónicas 7:14', 'gracia', 'Si se humillare mi pueblo', 6),
  v('2-cronicas-20-15', '2 Crónicas 20:15', 'fe-y-valor', 'No es vuestra la guerra, sino de Dios', 6),
  v('1-cronicas-4-10', '1 Crónicas 4:10', 'alabanza', 'Oh, si me dieras bendición', 6),
  v('1-cronicas-28-20', '1 Crónicas 28:20', 'fe-y-valor', 'Anímate y esfuérzate, y manos a la obra', 6),
  v('mateo-4-4', 'Mateo 4:4', 'sabiduria', 'No solo de pan vivirá el hombre', 6),
  v('mateo-4-19', 'Mateo 4:19', 'identidad', 'Os haré pescadores de hombres', 6),
  v('mateo-5-44', 'Mateo 5:44', 'amor', 'Amad a vuestros enemigos', 6),
  v('mateo-6-9', 'Mateo 6:9', 'alabanza', 'Padre nuestro que estás en los cielos', 6),
  v('mateo-6-11', 'Mateo 6:11', 'confianza', 'El pan nuestro de cada día', 6),
  v('mateo-6-28', 'Mateo 6:28', 'confianza', 'Considerad los lirios del campo', 6),
  v('mateo-7-24', 'Mateo 7:24', 'sabiduria', 'Edificó su casa sobre la roca', 6),
  v('mateo-8-26', 'Mateo 8:26', 'confianza', '¿Por qué teméis, hombres de poca fe?', 6),
  v('mateo-14-27', 'Mateo 14:27', 'fe-y-valor', 'Tened ánimo; yo soy, no temáis', 6),
  v('mateo-16-24', 'Mateo 16:24', 'identidad', 'Tome su cruz, y sígame', 6),
  v('mateo-16-16', 'Mateo 16:16', 'identidad', 'Tú eres el Cristo, el Hijo del Dios viviente', 6),
  v('mateo-17-20', 'Mateo 17:20', 'fe-y-valor', 'Fe como un grano de mostaza', 6),
  v('mateo-19-14', 'Mateo 19:14', 'amor', 'Dejad a los niños venir a mí', 6),
  v('mateo-25-21', 'Mateo 25:21', 'identidad', 'Bien, buen siervo y fiel', 6),
  v('mateo-26-41', 'Mateo 26:41', 'sabiduria', 'Velad y orad', 6),
  v('mateo-28-6', 'Mateo 28:6', 'esperanza', 'No está aquí, pues ha resucitado', 6),
  v('mateo-3-17', 'Mateo 3:17', 'identidad', 'Este es mi Hijo amado', 6),
  v('mateo-1-23', 'Mateo 1:23', 'alabanza', 'Dios con nosotros', 6),
  v('mateo-10-30', 'Mateo 10:30', 'identidad', 'Aun vuestros cabellos están todos contados', 6),
  v('mateo-26-26', 'Mateo 26:26', 'gracia', 'Tomad, comed; esto es mi cuerpo', 6),
  v('mateo-10-8', 'Mateo 10:8', 'amor', 'De gracia recibisteis, dad de gracia', 6),
  v('marcos-9-24', 'Marcos 9:24', 'fe-y-valor', 'Creo; ayuda mi incredulidad', 6),
  v('marcos-5-36', 'Marcos 5:36', 'fe-y-valor', 'No temas, cree solamente', 6),
  v('marcos-4-39', 'Marcos 4:39', 'confianza', 'Calla, enmudece', 6),
  v('marcos-16-15', 'Marcos 16:15', 'identidad', 'Id por todo el mundo', 6),
  v('marcos-6-31', 'Marcos 6:31', 'confianza', 'Descansad un poco', 6),
  v('marcos-11-22', 'Marcos 11:22', 'fe-y-valor', 'Tened fe en Dios', 6),
  v('lucas-1-38', 'Lucas 1:38', 'confianza', 'Hágase conmigo conforme a tu palabra', 6),
  v('lucas-1-45', 'Lucas 1:45', 'fe-y-valor', 'Bienaventurada la que creyó', 6),
  v('lucas-1-46-47', 'Lucas 1:46-47', 'alabanza', 'Engrandece mi alma al Señor', 6),
  v('lucas-2-14', 'Lucas 2:14', 'alabanza', 'Gloria a Dios en las alturas', 6),
  v('lucas-2-10', 'Lucas 2:10', 'alabanza', 'Os doy nuevas de gran gozo', 6),
  v('lucas-2-52', 'Lucas 2:52', 'sabiduria', 'Crecía en sabiduría y en estatura', 6),
  v('lucas-6-36', 'Lucas 6:36', 'gracia', 'Sed misericordiosos como vuestro Padre', 6),
  v('lucas-10-42', 'Lucas 10:42', 'confianza', 'Solo una cosa es necesaria', 6),
  v('lucas-12-32', 'Lucas 12:32', 'confianza', 'No temáis, manada pequeña', 6),
  v('lucas-15-20', 'Lucas 15:20', 'amor', 'Corrió, y se echó sobre su cuello', 6),
  v('lucas-15-24', 'Lucas 15:24', 'gracia', 'Era perdido, y es hallado', 6),
  v('lucas-19-10', 'Lucas 19:10', 'gracia', 'A buscar y a salvar lo que se había perdido', 6),
  v('lucas-22-19', 'Lucas 22:19', 'gracia', 'Haced esto en memoria de mí', 6),
  v('lucas-23-34', 'Lucas 23:34', 'gracia', 'Padre, perdónalos', 6),
  v('lucas-23-43', 'Lucas 23:43', 'esperanza', 'Hoy estarás conmigo en el paraíso', 6),
  v('lucas-23-46', 'Lucas 23:46', 'confianza', 'En tus manos encomiendo mi espíritu', 6),
  v('lucas-24-29', 'Lucas 24:29', 'confianza', 'Quédate con nosotros', 6),
  v('lucas-4-18', 'Lucas 4:18', 'identidad', 'El Espíritu del Señor está sobre mí', 6),
  v('lucas-5-5', 'Lucas 5:5', 'fe-y-valor', 'En tu palabra echaré la red', 6),
  v('lucas-17-21', 'Lucas 17:21', 'identidad', 'El reino de Dios está entre vosotros', 6),
  v('lucas-22-42', 'Lucas 22:42', 'confianza', 'No se haga mi voluntad, sino la tuya', 6),
  v('lucas-7-50', 'Lucas 7:50', 'gracia', 'Tu fe te ha salvado, ve en paz', 6),
  v('juan-1-29', 'Juan 1:29', 'gracia', 'He aquí el Cordero de Dios', 6),
  v('juan-1-16', 'Juan 1:16', 'gracia', 'Gracia sobre gracia', 6),
  v('juan-3-30', 'Juan 3:30', 'identidad', 'Es necesario que él crezca', 7),
  v('juan-4-14', 'Juan 4:14', 'gracia', 'El agua que yo le daré', 7),
  v('juan-6-68', 'Juan 6:68', 'identidad', 'Tú tienes palabras de vida eterna', 7),
  v('juan-10-27', 'Juan 10:27', 'identidad', 'Mis ovejas oyen mi voz', 7),
  v('juan-11-35', 'Juan 11:35', 'amor', 'Jesús lloró', 7),
  v('juan-11-40', 'Juan 11:40', 'fe-y-valor', 'Si crees, verás la gloria de Dios', 7),
  v('juan-14-2', 'Juan 14:2', 'esperanza', 'En la casa de mi Padre muchas moradas hay', 7),
  v('juan-14-18', 'Juan 14:18', 'confianza', 'No os dejaré huérfanos', 7),
  v('juan-14-26', 'Juan 14:26', 'identidad', 'El Consolador, el Espíritu Santo', 7),
  v('juan-15-11', 'Juan 15:11', 'alabanza', 'Vuestro gozo sea cumplido', 7),
  v('juan-15-15', 'Juan 15:15', 'identidad', 'Os he llamado amigos', 7),
  v('juan-15-16', 'Juan 15:16', 'identidad', 'Yo os elegí a vosotros', 7),
  v('juan-16-22', 'Juan 16:22', 'esperanza', 'Nadie os quitará vuestro gozo', 7),
  v('juan-17-17', 'Juan 17:17', 'sabiduria', 'Tu palabra es verdad', 7),
  v('juan-17-21', 'Juan 17:21', 'amor', 'Que todos sean uno', 7),
  v('juan-19-30', 'Juan 19:30', 'gracia', 'Consumado es', 7),
  v('juan-20-29', 'Juan 20:29', 'fe-y-valor', 'Bienaventurados los que no vieron, y creyeron', 7),
  v('juan-20-28', 'Juan 20:28', 'alabanza', '¡Señor mío, y Dios mío!', 7),
  v('juan-21-17', 'Juan 21:17', 'amor', 'Señor, tú sabes que te amo', 7),
  v('juan-13-7', 'Juan 13:7', 'confianza', 'Lo entenderás después', 7),
  v('juan-9-25', 'Juan 9:25', 'gracia', 'Habiendo yo sido ciego, ahora veo', 7),
  v('juan-3-3', 'Juan 3:3', 'gracia', 'El que no naciere de nuevo', 7),
  v('juan-2-5', 'Juan 2:5', 'sabiduria', 'Haced todo lo que os dijere', 7),
  v('juan-6-37', 'Juan 6:37', 'gracia', 'Al que a mí viene, no le echo fuera', 7),
  v('juan-7-38', 'Juan 7:38', 'identidad', 'Ríos de agua viva', 7),
  v('hechos-4-12', 'Hechos 4:12', 'gracia', 'En ningún otro hay salvación', 7),
  v('hechos-5-29', 'Hechos 5:29', 'fe-y-valor', 'Obedecer a Dios antes que a los hombres', 7),
  v('hechos-17-28', 'Hechos 17:28', 'identidad', 'En él vivimos, y nos movemos, y somos', 7),
  v('hechos-20-24', 'Hechos 20:24', 'fe-y-valor', 'Que acabe mi carrera con gozo', 7),
  v('hechos-20-35', 'Hechos 20:35', 'amor', 'Más bienaventurado es dar que recibir', 7),
  v('hechos-2-38', 'Hechos 2:38', 'gracia', 'Arrepentíos, y bautícese cada uno', 7),
  v('hechos-4-20', 'Hechos 4:20', 'identidad', 'No podemos dejar de decir lo que hemos visto', 7),
  v('hechos-18-9', 'Hechos 18:9', 'fe-y-valor', 'No temas, sino habla, y no calles', 7),
  v('hechos-10-34', 'Hechos 10:34', 'identidad', 'Dios no hace acepción de personas', 7),
  v('hechos-16-25', 'Hechos 16:25', 'alabanza', 'A medianoche cantaban himnos a Dios', 7),
  v('romanos-1-17', 'Romanos 1:17', 'gracia', 'El justo por la fe vivirá', 7),
  v('romanos-3-23-24', 'Romanos 3:23-24', 'gracia', 'Justificados gratuitamente por su gracia', 7),
  v('romanos-5-5', 'Romanos 5:5', 'esperanza', 'La esperanza no avergüenza', 7),
  v('romanos-6-4', 'Romanos 6:4', 'identidad', 'Andemos en vida nueva', 7),
  v('romanos-8-26', 'Romanos 8:26', 'confianza', 'El Espíritu nos ayuda en nuestra debilidad', 7),
  v('romanos-8-15', 'Romanos 8:15', 'identidad', 'Por el cual clamamos: ¡Abba, Padre!', 7),
  v('romanos-10-17', 'Romanos 10:17', 'fe-y-valor', 'La fe es por el oír', 7),
  v('romanos-10-13', 'Romanos 10:13', 'gracia', 'Todo aquel que invocare el nombre del Señor', 7),
  v('romanos-11-36', 'Romanos 11:36', 'alabanza', 'De él, y por él, y para él', 7),
  v('romanos-11-33', 'Romanos 11:33', 'alabanza', '¡Oh profundidad de las riquezas!', 7),
  v('romanos-13-10', 'Romanos 13:10', 'amor', 'El amor no hace mal al prójimo', 7),
  v('1-corintios-1-27', '1 Corintios 1:27', 'identidad', 'Lo necio del mundo escogió Dios', 7),
  v('1-corintios-6-20', '1 Corintios 6:20', 'identidad', 'Habéis sido comprados por precio', 7),
  v('1-corintios-9-24', '1 Corintios 9:24', 'fe-y-valor', 'Corred de tal manera que lo obtengáis', 7),
  v('1-corintios-13-12', '1 Corintios 13:12', 'esperanza', 'Ahora vemos por espejo, oscuramente', 7),
  v('1-corintios-13-2', '1 Corintios 13:2', 'amor', 'Si no tengo amor, nada soy', 7),
  v('1-corintios-15-55', '1 Corintios 15:55', 'esperanza', '¿Dónde está, oh muerte, tu aguijón?', 7),
  v('1-corintios-12-27', '1 Corintios 12:27', 'identidad', 'Vosotros sois el cuerpo de Cristo', 7),
  v('1-corintios-15-10', '1 Corintios 15:10', 'gracia', 'Por la gracia de Dios soy lo que soy', 7),
  v('1-corintios-3-6', '1 Corintios 3:6', 'sabiduria', 'Dios da el crecimiento', 7),
  v('1-corintios-14-33', '1 Corintios 14:33', 'sabiduria', 'Dios no es Dios de confusión, sino de paz', 7),
  v('2-corintios-4-8', '2 Corintios 4:8', 'fe-y-valor', 'Atribulados en todo, mas no angustiados', 7),
  v('juan-1-3', 'Juan 1:3', 'alabanza', 'Todas las cosas por él fueron hechas', 7),
  v('2-corintios-9-15', '2 Corintios 9:15', 'alabanza', 'Gracias a Dios por su don inefable', 7),
  v('2-corintios-13-14', '2 Corintios 13:14', 'gracia', 'La gracia del Señor Jesucristo', 7),
  v('2-corintios-6-2', '2 Corintios 6:2', 'gracia', 'He aquí ahora el día de salvación', 7),
  v('2-corintios-10-5', '2 Corintios 10:5', 'sabiduria', 'Llevando cautivo todo pensamiento', 7),
  v('2-corintios-5-14', '2 Corintios 5:14', 'amor', 'El amor de Cristo nos constriñe', 7),
  v('2-corintios-5-20', '2 Corintios 5:20', 'identidad', 'Somos embajadores en nombre de Cristo', 7),
  v('galatas-4-7', 'Gálatas 4:7', 'identidad', 'Ya no eres esclavo, sino hijo', 7),
  v('galatas-5-25', 'Gálatas 5:25', 'identidad', 'Andemos también por el Espíritu', 7),
  v('galatas-6-14', 'Gálatas 6:14', 'gracia', 'Lejos esté de mí gloriarme, sino en la cruz', 7),
  v('efesios-1-4', 'Efesios 1:4', 'identidad', 'Nos escogió en él', 7),
  v('efesios-2-4-5', 'Efesios 2:4-5', 'gracia', 'Dios, que es rico en misericordia', 7),
  v('efesios-4-3', 'Efesios 4:3', 'amor', 'En el vínculo de la paz', 7),
  v('efesios-4-5', 'Efesios 4:5', 'identidad', 'Un Señor, una fe, un bautismo', 7),
  v('efesios-5-2', 'Efesios 5:2', 'amor', 'Andad en amor, como también Cristo nos amó', 7),
  v('efesios-5-19', 'Efesios 5:19', 'alabanza', 'Alabando al Señor en vuestros corazones', 7),
  v('efesios-5-25', 'Efesios 5:25', 'amor', 'Maridos, amad a vuestras mujeres', 7),
  v('efesios-6-16', 'Efesios 6:16', 'fe-y-valor', 'El escudo de la fe', 7),
  v('efesios-1-7', 'Efesios 1:7', 'gracia', 'Tenemos redención por su sangre', 7),
  v('efesios-2-14', 'Efesios 2:14', 'gracia', 'Él es nuestra paz', 7),
  v('filipenses-1-3', 'Filipenses 1:3', 'amor', 'Siempre que me acuerdo de vosotros', 7),
  v('filipenses-4-4', 'Filipenses 4:4', 'alabanza', 'Regocijaos en el Señor siempre', 7),
  v('filipenses-3-10', 'Filipenses 3:10', 'identidad', 'A fin de conocerle', 7),
  v('filipenses-3-20', 'Filipenses 3:20', 'identidad', 'Nuestra ciudadanía está en los cielos', 7),
  v('filipenses-2-9', 'Filipenses 2:9', 'alabanza', 'Un nombre que es sobre todo nombre', 7),
  v('filipenses-4-5', 'Filipenses 4:5', 'esperanza', 'El Señor está cerca', 7),
  v('colosenses-1-17', 'Colosenses 1:17', 'alabanza', 'Todas las cosas en él subsisten', 7),
  v('colosenses-2-7', 'Colosenses 2:7', 'identidad', 'Arraigados y sobreedificados en él', 7),
  v('colosenses-4-6', 'Colosenses 4:6', 'sabiduria', 'Sea vuestra palabra siempre con gracia', 7),
  v('1-tesalonicenses-5-24', '1 Tesalonicenses 5:24', 'confianza', 'Fiel es el que os llama', 7),
  v('1-tesalonicenses-5-21', '1 Tesalonicenses 5:21', 'sabiduria', 'Examinadlo todo; retened lo bueno', 7),
  v('1-tesalonicenses-4-17', '1 Tesalonicenses 4:17', 'esperanza', 'Así estaremos siempre con el Señor', 7),
  v('1-tesalonicenses-4-11', '1 Tesalonicenses 4:11', 'sabiduria', 'Que procuréis tener tranquilidad', 7),
  v('2-tesalonicenses-3-3', '2 Tesalonicenses 3:3', 'confianza', 'Fiel es el Señor, que os afirmará', 7),
  v('2-tesalonicenses-3-16', '2 Tesalonicenses 3:16', 'confianza', 'El Señor de paz os dé siempre paz', 7),
  v('1-timoteo-4-12', '1 Timoteo 4:12', 'identidad', 'Ninguno tenga en poco tu juventud', 7),
  v('1-timoteo-6-6', '1 Timoteo 6:6', 'sabiduria', 'Gran ganancia es la piedad', 7),
  v('1-timoteo-6-12', '1 Timoteo 6:12', 'fe-y-valor', 'Echa mano de la vida eterna', 7),
  v('1-timoteo-1-15', '1 Timoteo 1:15', 'gracia', 'Para salvar a los pecadores', 7),
  v('1-timoteo-1-17', '1 Timoteo 1:17', 'alabanza', 'Al Rey de los siglos, inmortal, invisible', 7),
  v('2-timoteo-1-12', '2 Timoteo 1:12', 'confianza', 'Yo sé a quién he creído', 7),
  v('2-timoteo-2-22', '2 Timoteo 2:22', 'sabiduria', 'Huye también de las pasiones juveniles', 7),
  v('2-timoteo-1-5', '2 Timoteo 1:5', 'identidad', 'La fe no fingida que hay en ti', 7),
  v('2-timoteo-2-1', '2 Timoteo 2:1', 'gracia', 'Esfuérzate en la gracia', 8),
  v('2-timoteo-4-2', '2 Timoteo 4:2', 'identidad', 'Que prediques la palabra', 8),
  v('tito-2-11', 'Tito 2:11', 'gracia', 'La gracia de Dios se ha manifestado', 8),
  v('tito-3-5', 'Tito 3:5', 'gracia', 'Nos salvó, no por obras de justicia', 8),
  v('filemon-1-7', 'Filemón 1:7', 'amor', 'Gran gozo y consolación en tu amor', 8),
  v('hebreos-4-12', 'Hebreos 4:12', 'sabiduria', 'La palabra de Dios es viva y eficaz', 8),
  v('hebreos-13-1', 'Hebreos 13:1', 'amor', 'Permanezca el amor fraternal', 8),
  v('hebreos-6-19', 'Hebreos 6:19', 'esperanza', 'Como segura y firme ancla del alma', 8),
  v('hebreos-13-15', 'Hebreos 13:15', 'alabanza', 'Sacrificio de alabanza', 8),
  v('hebreos-10-35', 'Hebreos 10:35', 'fe-y-valor', 'No perdáis, pues, vuestra confianza', 8),
  v('santiago-4-7', 'Santiago 4:7', 'fe-y-valor', 'Resistid al diablo, y huirá de vosotros', 8),
  v('santiago-5-16', 'Santiago 5:16', 'gracia', 'La oración eficaz del justo puede mucho', 8),
  v('santiago-2-17', 'Santiago 2:17', 'sabiduria', 'La fe, si no tiene obras, es muerta', 8),
  v('santiago-4-14', 'Santiago 4:14', 'sabiduria', '¿Qué es vuestra vida? Es neblina', 8),
  v('santiago-5-13', 'Santiago 5:13', 'alabanza', '¿Está alguno alegre? Cante alabanzas', 8),
  v('santiago-3-17', 'Santiago 3:17', 'sabiduria', 'La sabiduría que es de lo alto', 8),
  v('1-pedro-1-3', '1 Pedro 1:3', 'esperanza', 'Una esperanza viva', 8),
  v('1-pedro-1-16', '1 Pedro 1:16', 'identidad', 'Sed santos, porque yo soy santo', 8),
  v('1-pedro-5-10', '1 Pedro 5:10', 'esperanza', 'Él mismo os perfeccione, afirme, fortalezca', 8),
  v('1-pedro-3-4', '1 Pedro 3:4', 'identidad', 'El incorruptible ornato de un espíritu afable', 8),
  v('2-pedro-3-9', '2 Pedro 3:9', 'gracia', 'El Señor no retarda su promesa', 8),
  v('2-pedro-3-8', '2 Pedro 3:8', 'sabiduria', 'Un día es como mil años', 8),
  v('2-pedro-3-18', '2 Pedro 3:18', 'gracia', 'Creced en la gracia y el conocimiento', 8),
  v('1-juan-4-4', '1 Juan 4:4', 'fe-y-valor', 'Mayor es el que está en vosotros', 8),
  v('1-juan-3-16', '1 Juan 3:16', 'amor', 'En esto hemos conocido el amor', 8),
  v('1-juan-1-5', '1 Juan 1:5', 'alabanza', 'Dios es luz', 8),
  v('1-juan-4-7', '1 Juan 4:7', 'amor', 'El amor es de Dios', 8),
  v('3-juan-1-2', '3 Juan 1:2', 'alabanza', 'Que seas prosperado en todas las cosas', 8),
  v('3-juan-1-4', '3 Juan 1:4', 'amor', 'No tengo yo mayor gozo que este', 8),
  v('judas-1-24', 'Judas 1:24', 'confianza', 'Poderoso para guardaros sin caída', 8),
  v('judas-1-21', 'Judas 1:21', 'amor', 'Conservaos en el amor de Dios', 8),
  v('apocalipsis-2-10', 'Apocalipsis 2:10', 'fe-y-valor', 'Sé fiel hasta la muerte', 8),
  v('apocalipsis-4-11', 'Apocalipsis 4:11', 'alabanza', 'Digno eres de recibir la gloria', 8),
  v('apocalipsis-21-3', 'Apocalipsis 21:3', 'esperanza', 'El tabernáculo de Dios con los hombres', 8),
  v('apocalipsis-22-20', 'Apocalipsis 22:20', 'esperanza', 'Ven, Señor Jesús', 8),
  v('apocalipsis-5-12', 'Apocalipsis 5:12', 'alabanza', 'El Cordero que fue inmolado es digno', 8),
  v('apocalipsis-19-16', 'Apocalipsis 19:16', 'alabanza', 'Rey de reyes y Señor de señores', 8),
  v('salmo-8-3', 'Salmo 8:3', 'alabanza', 'Cuando veo tus cielos, obra de tus dedos', 8),
  v('salmo-5-3', 'Salmo 5:3', 'alabanza', 'De mañana oirás mi voz', 8),
  v('salmo-5-11', 'Salmo 5:11', 'alabanza', 'Alégrense todos los que en ti confían', 8),
  v('salmo-9-9', 'Salmo 9:9', 'esperanza', 'Refugio para el tiempo de angustia', 8),
  v('salmo-9-10', 'Salmo 9:10', 'confianza', 'En ti confiarán los que conocen tu nombre', 8),
  v('salmo-13-5', 'Salmo 13:5', 'confianza', 'Mas yo en tu misericordia he confiado', 8),
  v('salmo-16-1', 'Salmo 16:1', 'confianza', 'Guárdame, oh Dios, porque en ti he confiado', 8),
  v('salmo-16-8', 'Salmo 16:8', 'confianza', 'Al Señor he puesto siempre delante de mí', 8),
  v('salmo-17-8', 'Salmo 17:8', 'confianza', 'Guárdame como a la niña de tus ojos', 8),
  v('salmo-18-1', 'Salmo 18:1', 'alabanza', 'Te amo, oh Señor, fortaleza mía', 8),
  v('salmo-18-29', 'Salmo 18:29', 'fe-y-valor', 'Con mi Dios asaltaré muros', 8),
  v('salmo-18-30', 'Salmo 18:30', 'confianza', 'En cuanto a Dios, perfecto es su camino', 8),
  v('salmo-18-32', 'Salmo 18:32', 'fe-y-valor', 'Dios es el que me ciñe de poder', 8),
  v('salmo-18-28', 'Salmo 18:28', 'esperanza', 'Tú encenderás mi lámpara', 8),
  v('salmo-19-7', 'Salmo 19:7', 'sabiduria', 'La ley del Señor es perfecta', 8),
  v('salmo-24-1', 'Salmo 24:1', 'alabanza', 'Del Señor es la tierra y su plenitud', 8),
  v('salmo-24-7', 'Salmo 24:7', 'alabanza', 'Alzad, oh puertas, vuestras cabezas', 8),
  v('salmo-25-1', 'Salmo 25:1', 'alabanza', 'A ti, oh Señor, levantaré mi alma', 8),
  v('salmo-25-4', 'Salmo 25:4', 'sabiduria', 'Muéstrame, oh Señor, tus caminos', 8),
  v('salmo-27-8', 'Salmo 27:8', 'alabanza', 'Tu rostro buscaré, oh Señor', 8),
  v('salmo-27-13', 'Salmo 27:13', 'esperanza', 'Si no creyese que veo la bondad del Señor', 8),
  v('salmo-29-2', 'Salmo 29:2', 'alabanza', 'En la hermosura de la santidad', 8),
  v('salmo-29-11', 'Salmo 29:11', 'esperanza', 'El Señor bendecirá a su pueblo con paz', 8),
  v('salmo-31-19', 'Salmo 31:19', 'alabanza', '¡Cuán grande es tu bondad!', 8),
  v('salmo-32-1', 'Salmo 32:1', 'gracia', 'Aquel cuya transgresión ha sido perdonada', 8),
  v('salmo-32-7', 'Salmo 32:7', 'confianza', 'Me guardarás de la angustia', 8),
  v('salmo-33-20', 'Salmo 33:20', 'confianza', 'Nuestra ayuda y nuestro escudo es él', 8),
  v('salmo-34-3', 'Salmo 34:3', 'alabanza', 'Engrandeced al Señor conmigo', 8),
  v('salmo-34-5', 'Salmo 34:5', 'esperanza', 'Los que miraron a él fueron alumbrados', 8),
  v('salmo-34-19', 'Salmo 34:19', 'fe-y-valor', 'De todas ellas le librará el Señor', 8),
  v('salmo-36-5', 'Salmo 36:5', 'amor', 'Hasta los cielos llega tu misericordia', 8),
  v('salmo-36-9', 'Salmo 36:9', 'alabanza', 'En tu luz veremos la luz', 8),
  v('salmo-39-7', 'Salmo 39:7', 'esperanza', 'Mi esperanza está en ti', 8),
  v('salmo-40-2', 'Salmo 40:2', 'gracia', 'Puso mis pies sobre peña', 8),
  v('salmo-43-3', 'Salmo 43:3', 'sabiduria', 'Envía tu luz y tu verdad', 8),
  v('salmo-47-1', 'Salmo 47:1', 'alabanza', 'Pueblos todos, batid las manos', 8),
  v('salmo-50-15', 'Salmo 50:15', 'confianza', 'Invócame en el día de la angustia', 8),
  v('salmo-51-17', 'Salmo 51:17', 'gracia', 'Corazón contrito y humillado', 8),
  v('salmo-54-4', 'Salmo 54:4', 'confianza', 'He aquí, Dios es el que me ayuda', 8),
  v('salmo-55-17', 'Salmo 55:17', 'fe-y-valor', 'Tarde y mañana y a mediodía oraré', 8),
  v('salmo-56-8', 'Salmo 56:8', 'esperanza', 'Pon mis lágrimas en tu redoma', 8),
  v('salmo-57-7', 'Salmo 57:7', 'alabanza', 'Pronto está mi corazón, oh Dios', 8),
  v('salmo-59-16', 'Salmo 59:16', 'alabanza', 'Yo cantaré de tu poder', 8),
  v('salmo-60-12', 'Salmo 60:12', 'fe-y-valor', 'En Dios haremos proezas', 8),
  v('salmo-63-7', 'Salmo 63:7', 'alabanza', 'En la sombra de tus alas me regocijaré', 8),
  v('salmo-65-11', 'Salmo 65:11', 'alabanza', 'Tú coronas el año con tus bienes', 8),
  v('salmo-66-1', 'Salmo 66:1', 'alabanza', 'Aclamad a Dios con alegría, toda la tierra', 8),
  v('salmo-67-1', 'Salmo 67:1', 'alabanza', 'Dios tenga misericordia de nosotros', 8),
  v('salmo-68-5', 'Salmo 68:5', 'amor', 'Padre de huérfanos y defensor de viudas', 8),
  v('salmo-68-19', 'Salmo 68:19', 'alabanza', 'Cada día nos colma de beneficios', 8),
  v('salmo-69-30', 'Salmo 69:30', 'alabanza', 'Alabaré yo el nombre de Dios con cántico', 8),
  v('salmo-71-5', 'Salmo 71:5', 'esperanza', 'Tú, oh Señor, eres mi esperanza', 8),
  v('salmo-73-25', 'Salmo 73:25', 'alabanza', '¿A quién tengo yo en los cielos sino a ti?', 8),
  v('salmo-73-28', 'Salmo 73:28', 'confianza', 'El acercarme a Dios es el bien', 8),
  v('salmo-77-14', 'Salmo 77:14', 'alabanza', 'Tú eres el Dios que hace maravillas', 8),
  v('salmo-80-3', 'Salmo 80:3', 'gracia', 'Haz resplandecer tu rostro, y seremos salvos', 8),
  v('salmo-81-10', 'Salmo 81:10', 'confianza', 'Abre tu boca, y yo la llenaré', 8),
  v('salmo-84-1', 'Salmo 84:1', 'alabanza', '¡Cuán amables son tus moradas!', 8),
  v('salmo-85-10', 'Salmo 85:10', 'amor', 'La misericordia y la verdad se encontraron', 8),
  v('salmo-86-5', 'Salmo 86:5', 'gracia', 'Tú, Señor, eres bueno y perdonador', 8),
  v('salmo-86-11', 'Salmo 86:11', 'sabiduria', 'Caminaré yo en tu verdad', 8),
  v('salmo-89-1', 'Salmo 89:1', 'alabanza', 'Las misericordias del Señor cantaré', 8),
  v('salmo-89-15', 'Salmo 89:15', 'alabanza', 'Bienaventurado el pueblo que sabe aclamarte', 8),
  v('salmo-90-1', 'Salmo 90:1', 'confianza', 'Tú nos has sido refugio', 9),
  v('salmo-90-2', 'Salmo 90:2', 'alabanza', 'Desde el siglo y hasta el siglo, tú eres Dios', 9),
  v('salmo-90-14', 'Salmo 90:14', 'alabanza', 'De mañana sácianos de tu misericordia', 9),
  v('salmo-90-17', 'Salmo 90:17', 'sabiduria', 'La obra de nuestras manos confirma', 9),
  v('salmo-91-5', 'Salmo 91:5', 'fe-y-valor', 'No temerás el terror nocturno', 9),
  v('salmo-91-16', 'Salmo 91:16', 'esperanza', 'Lo saciaré de larga vida', 9),
  v('salmo-92-1', 'Salmo 92:1', 'alabanza', 'Bueno es alabarte, oh Señor', 9),
  v('salmo-92-12', 'Salmo 92:12', 'esperanza', 'El justo florecerá como la palmera', 9),
  v('salmo-94-19', 'Salmo 94:19', 'esperanza', 'Tus consolaciones alegraban mi alma', 9),
  v('salmo-95-6', 'Salmo 95:6', 'alabanza', 'Venid, adoremos y postrémonos', 9),
  v('salmo-96-1', 'Salmo 96:1', 'alabanza', 'Cantad al Señor cántico nuevo', 9),
  v('salmo-97-11', 'Salmo 97:11', 'esperanza', 'Luz está sembrada para el justo', 9),
  v('salmo-100-2', 'Salmo 100:2', 'alabanza', 'Servid al Señor con alegría', 9),
  v('salmo-101-2', 'Salmo 101:2', 'sabiduria', 'En la integridad de mi corazón andaré', 9),
  v('salmo-103-4', 'Salmo 103:4', 'gracia', 'El que te corona de favores y misericordias', 9),
  v('salmo-104-24', 'Salmo 104:24', 'alabanza', '¡Cuán innumerables son tus obras!', 9),
  v('salmo-104-33', 'Salmo 104:33', 'alabanza', 'Al Señor cantaré en mi vida', 9),
  v('salmo-107-29', 'Salmo 107:29', 'confianza', 'Cambia la tempestad en sosiego', 9),
  v('salmo-113-3', 'Salmo 113:3', 'alabanza', 'Desde el nacimiento del sol', 9),
  v('salmo-115-1', 'Salmo 115:1', 'alabanza', 'Sino a tu nombre da gloria', 9),
  v('salmo-116-1', 'Salmo 116:1', 'amor', 'Amo al Señor, pues ha oído mi voz', 9),
  v('salmo-116-7', 'Salmo 116:7', 'confianza', 'Vuelve, oh alma mía, a tu reposo', 9),
  v('salmo-116-12', 'Salmo 116:12', 'alabanza', '¿Qué pagaré al Señor?', 9),
  v('salmo-117-1', 'Salmo 117:1', 'alabanza', 'Alabad al Señor, naciones todas', 9),
  v('salmo-118-17', 'Salmo 118:17', 'fe-y-valor', 'No moriré, sino que viviré', 9),
  v('salmo-118-22', 'Salmo 118:22', 'identidad', 'La piedra que desecharon los edificadores', 9),
  v('salmo-119-73', 'Salmo 119:73', 'identidad', 'Tus manos me hicieron y me formaron', 9),
  v('salmo-119-97', 'Salmo 119:97', 'sabiduria', '¡Oh, cuánto amo yo tu ley!', 9),
  v('salmo-121-3', 'Salmo 121:3', 'confianza', 'Ni se dormirá el que te guarda', 9),
  v('salmo-122-1', 'Salmo 122:1', 'alabanza', 'A la casa del Señor iremos', 9),
  v('salmo-125-1', 'Salmo 125:1', 'confianza', 'Como el monte de Sion, que no se mueve', 9),
  v('salmo-128-3', 'Salmo 128:3', 'amor', 'Tus hijos como plantas de olivo', 9),
  v('salmo-130-5', 'Salmo 130:5', 'esperanza', 'Esperé yo al Señor, esperó mi alma', 9),
  v('salmo-131-2', 'Salmo 131:2', 'confianza', 'Como un niño destetado de su madre', 9),
  v('salmo-138-3', 'Salmo 138:3', 'confianza', 'El día que clamé, me respondiste', 9),
  v('salmo-138-8', 'Salmo 138:8', 'confianza', 'El Señor cumplirá su propósito en mí', 9),
  v('salmo-139-5', 'Salmo 139:5', 'confianza', 'Detrás y delante me rodeaste', 9),
  v('salmo-139-9-10', 'Salmo 139:9-10', 'confianza', 'Aun allí me guiará tu mano', 9),
  v('salmo-139-12', 'Salmo 139:12', 'esperanza', 'Aun las tinieblas no encubren de ti', 9),
  v('salmo-139-16', 'Salmo 139:16', 'identidad', 'Mi embrión vieron tus ojos', 9),
  v('salmo-139-17', 'Salmo 139:17', 'alabanza', '¡Cuán preciosos me son tus pensamientos!', 9),
  v('salmo-141-3', 'Salmo 141:3', 'sabiduria', 'Pon guarda a mi boca', 9),
  v('salmo-143-10', 'Salmo 143:10', 'sabiduria', 'Enséñame a hacer tu voluntad', 9),
  v('salmo-144-1', 'Salmo 144:1', 'fe-y-valor', 'Quien adiestra mis manos para la batalla', 9),
  v('salmo-145-3', 'Salmo 145:3', 'alabanza', 'Digno de suprema alabanza', 9),
  v('salmo-145-9', 'Salmo 145:9', 'amor', 'Bueno es el Señor para con todos', 9),
  v('salmo-145-14', 'Salmo 145:14', 'esperanza', 'Sostiene el Señor a todos los que caen', 9),
  v('salmo-146-5', 'Salmo 146:5', 'confianza', 'Cuyo ayudador es el Dios de Jacob', 9),
  v('salmo-147-4', 'Salmo 147:4', 'alabanza', 'Él cuenta el número de las estrellas', 9),
  v('salmo-147-11', 'Salmo 147:11', 'amor', 'Se complace el Señor en los que le temen', 9),
  v('salmo-149-3', 'Salmo 149:3', 'alabanza', 'Alaben su nombre con danza', 9),
  v('salmo-149-4', 'Salmo 149:4', 'identidad', 'El Señor tiene contentamiento en su pueblo', 9),
  v('salmo-150-1', 'Salmo 150:1', 'alabanza', 'Alabad a Dios en su santuario', 9),
  v('salmo-1-3', 'Salmo 1:3', 'esperanza', 'Todo lo que hace prosperará', 9),
  v('salmo-3-5', 'Salmo 3:5', 'confianza', 'Yo me acosté y dormí, y desperté', 9),
  v('proverbios-23-26', 'Proverbios 23:26', 'amor', 'Dame, hijo mío, tu corazón', 9),
  v('proverbios-8-17', 'Proverbios 8:17', 'amor', 'Yo amo a los que me aman', 9),
  v('proverbios-3-9', 'Proverbios 3:9', 'sabiduria', 'Honra al Señor con tus bienes', 9),
  v('proverbios-4-7', 'Proverbios 4:7', 'sabiduria', 'Sabiduría ante todo; adquiere sabiduría', 9),
  v('proverbios-12-25', 'Proverbios 12:25', 'esperanza', 'La buena palabra lo alegra', 9),
  v('proverbios-17-6', 'Proverbios 17:6', 'amor', 'Corona de los viejos son los nietos', 9),
  v('proverbios-23-18', 'Proverbios 23:18', 'esperanza', 'Tu esperanza no será cortada', 9),
  v('proverbios-25-11', 'Proverbios 25:11', 'sabiduria', 'Manzana de oro con figuras de plata', 9),
  v('proverbios-30-5', 'Proverbios 30:5', 'confianza', 'Toda palabra de Dios es limpia', 9),
  v('proverbios-31-26', 'Proverbios 31:26', 'sabiduria', 'Abre su boca con sabiduría', 9),
  v('proverbios-31-29', 'Proverbios 31:29', 'amor', 'Mas tú sobrepasas a todas', 9),
  v('proverbios-6-6', 'Proverbios 6:6', 'sabiduria', 'Ve a la hormiga, oh perezoso', 9),
  v('proverbios-27-9', 'Proverbios 27:9', 'amor', 'El ungüento y el perfume alegran el corazón', 9),
  v('proverbios-12-4', 'Proverbios 12:4', 'amor', 'La mujer virtuosa es corona de su marido', 9),
  v('proverbios-3-3', 'Proverbios 3:3', 'sabiduria', 'Escríbelas en la tabla de tu corazón', 9),
  v('proverbios-13-12', 'Proverbios 13:12', 'esperanza', 'Árbol de vida es el deseo cumplido', 9),
  v('eclesiastes-3-4', 'Eclesiastés 3:4', 'esperanza', 'Tiempo de llorar, y tiempo de reír', 9),
  v('eclesiastes-11-1', 'Eclesiastés 11:1', 'sabiduria', 'Echa tu pan sobre las aguas', 9),
  v('eclesiastes-12-13', 'Eclesiastés 12:13', 'sabiduria', 'Teme a Dios, y guarda sus mandamientos', 9),
  v('eclesiastes-9-7', 'Eclesiastés 9:7', 'alabanza', 'Anda, y come tu pan con gozo', 9),
  v('eclesiastes-7-8', 'Eclesiastés 7:8', 'sabiduria', 'Mejor es el fin del negocio que su principio', 9),
  v('cantares-4-7', 'Cantares 4:7', 'amor', 'Toda tú eres hermosa, amiga mía', 9),
  v('cantares-2-4', 'Cantares 2:4', 'amor', 'Su bandera sobre mí fue amor', 9),
  v('cantares-3-4', 'Cantares 3:4', 'amor', 'Hallé luego al que ama mi alma', 9),
  v('cantares-2-11', 'Cantares 2:11', 'esperanza', 'Porque he aquí ha pasado el invierno', 9),
  v('cantares-5-16', 'Cantares 5:16', 'amor', 'Tal es mi amado, tal es mi amigo', 9),
  v('genesis-1-3', 'Génesis 1:3', 'esperanza', 'Sea la luz', 9),
  v('genesis-1-31', 'Génesis 1:31', 'alabanza', 'Era bueno en gran manera', 9),
  v('genesis-9-13', 'Génesis 9:13', 'esperanza', 'Mi arco he puesto en las nubes', 9),
  v('genesis-15-1', 'Génesis 15:1', 'confianza', 'Yo soy tu escudo', 9),
  v('genesis-15-5', 'Génesis 15:5', 'esperanza', 'Mira ahora los cielos, y cuenta las estrellas', 9),
  v('genesis-31-49', 'Génesis 31:49', 'amor', 'Atalaye el Señor entre tú y yo', 9),
  v('genesis-32-26', 'Génesis 32:26', 'fe-y-valor', 'No te dejaré, si no me bendices', 9),
  v('genesis-21-6', 'Génesis 21:6', 'alabanza', 'Dios me ha hecho reír', 9),
  v('genesis-8-22', 'Génesis 8:22', 'esperanza', 'Mientras la tierra permanezca', 9),
  v('exodo-4-12', 'Éxodo 4:12', 'fe-y-valor', 'Yo estaré con tu boca', 9),
  v('exodo-15-2', 'Éxodo 15:2', 'alabanza', 'Este es mi Dios, y lo alabaré', 9),
  v('exodo-15-11', 'Éxodo 15:11', 'alabanza', '¿Quién como tú, magnífico en santidad?', 9),
  v('exodo-20-3', 'Éxodo 20:3', 'sabiduria', 'No tendrás dioses ajenos delante de mí', 9),
  v('exodo-23-20', 'Éxodo 23:20', 'confianza', 'Yo envío mi Ángel delante de ti', 9),
  v('levitico-26-12', 'Levítico 26:12', 'identidad', 'Andaré entre vosotros', 9),
  v('deuteronomio-7-9', 'Deuteronomio 7:9', 'confianza', 'Dios fiel, que guarda el pacto', 9),
  v('deuteronomio-6-7', 'Deuteronomio 6:7', 'sabiduria', 'Las repetirás a tus hijos', 9),
  v('deuteronomio-28-2', 'Deuteronomio 28:2', 'alabanza', 'Vendrán sobre ti todas estas bendiciones', 9),
  v('deuteronomio-32-4', 'Deuteronomio 32:4', 'confianza', 'Él es la Roca, cuya obra es perfecta', 9),
  v('deuteronomio-33-25', 'Deuteronomio 33:25', 'fe-y-valor', 'Como tus días serán tus fuerzas', 10),
  v('deuteronomio-33-12', 'Deuteronomio 33:12', 'amor', 'El amado del Señor habitará confiado', 10),
  v('josue-3-5', 'Josué 3:5', 'identidad', 'Santificaos, porque el Señor hará maravillas', 10),
  v('josue-21-45', 'Josué 21:45', 'confianza', 'No faltó palabra de todas las buenas promesas', 10),
  v('jueces-6-12', 'Jueces 6:12', 'fe-y-valor', 'Varón esforzado y valiente', 10),
  v('jueces-6-14', 'Jueces 6:14', 'fe-y-valor', 'Ve con esta tu fuerza', 10),
  v('jueces-5-31', 'Jueces 5:31', 'amor', 'Como el sol cuando sale en su fuerza', 10),
  v('rut-2-12', 'Rut 2:12', 'confianza', 'Bajo cuyas alas has venido a refugiarte', 10),
  v('1-samuel-2-2', '1 Samuel 2:2', 'alabanza', 'No hay santo como el Señor', 10),
  v('1-samuel-18-1', '1 Samuel 18:1', 'amor', 'Lo amó Jonatán como a sí mismo', 10),
  v('1-samuel-30-6', '1 Samuel 30:6', 'fe-y-valor', 'David se fortaleció en el Señor su Dios', 10),
  v('1-samuel-17-45', '1 Samuel 17:45', 'fe-y-valor', 'Yo vengo a ti en el nombre del Señor', 10),
  v('1-samuel-15-22', '1 Samuel 15:22', 'sabiduria', 'El obedecer es mejor que los sacrificios', 10),
  v('1-reyes-3-9', '1 Reyes 3:9', 'sabiduria', 'Da, pues, a tu siervo corazón entendido', 10),
  v('1-reyes-2-2', '1 Reyes 2:2', 'fe-y-valor', 'Esfuérzate, y sé hombre', 10),
  v('2-reyes-6-16', '2 Reyes 6:16', 'fe-y-valor', 'Más son los que están con nosotros', 10),
  v('2-reyes-20-5', '2 Reyes 20:5', 'esperanza', 'He oído tu oración, y he visto tus lágrimas', 10),
  v('1-cronicas-16-11', '1 Crónicas 16:11', 'confianza', 'Buscad su rostro continuamente', 10),
  v('1-cronicas-29-11', '1 Crónicas 29:11', 'alabanza', 'Tuya es, oh Señor, la magnificencia', 10),
  v('1-cronicas-29-13', '1 Crónicas 29:13', 'alabanza', 'Alabamos y loamos tu glorioso nombre', 10),
  v('2-cronicas-16-9', '2 Crónicas 16:9', 'confianza', 'Los ojos del Señor contemplan toda la tierra', 10),
  v('2-cronicas-15-7', '2 Crónicas 15:7', 'fe-y-valor', 'Hay recompensa para vuestra obra', 10),
  v('2-cronicas-20-12', '2 Crónicas 20:12', 'confianza', 'A ti volvemos nuestros ojos', 10),
  v('2-cronicas-20-20', '2 Crónicas 20:20', 'fe-y-valor', 'Creed en el Señor, y estaréis seguros', 10),
  v('esdras-8-22', 'Esdras 8:22', 'confianza', 'La mano de nuestro Dios es para bien', 10),
  v('nehemias-2-20', 'Nehemías 2:20', 'fe-y-valor', 'El Dios de los cielos nos prosperará', 10),
  v('nehemias-6-3', 'Nehemías 6:3', 'sabiduria', 'Yo hago una gran obra, y no puedo ir', 10),
  v('job-23-10', 'Job 23:10', 'fe-y-valor', 'Saldré como oro', 10),
  v('job-33-4', 'Job 33:4', 'identidad', 'El espíritu de Dios me hizo', 10),
  v('job-8-21', 'Job 8:21', 'esperanza', 'Aún llenará tu boca de risa', 10),
  v('job-11-18', 'Job 11:18', 'esperanza', 'Tendrás confianza, porque hay esperanza', 10),
  v('job-42-5', 'Job 42:5', 'alabanza', 'Mas ahora mis ojos te ven', 10),
  v('job-12-10', 'Job 12:10', 'alabanza', 'En su mano está el alma de todo viviente', 10),
  v('job-37-14', 'Job 37:14', 'alabanza', 'Considera las maravillas de Dios', 10),
  v('isaias-6-3', 'Isaías 6:3', 'alabanza', 'Santo, santo, santo', 10),
  v('isaias-40-1', 'Isaías 40:1', 'esperanza', 'Consolaos, consolaos, pueblo mío', 10),
  v('isaias-42-3', 'Isaías 42:3', 'gracia', 'No quebrará la caña cascada', 10),
  v('isaias-43-25', 'Isaías 43:25', 'gracia', 'No me acordaré de tus pecados', 10),
  v('isaias-44-22', 'Isaías 44:22', 'gracia', 'Deshice como una nube tus rebeliones', 10),
  v('isaias-45-22', 'Isaías 45:22', 'gracia', 'Mirad a mí, y sed salvos', 10),
  v('isaias-48-17', 'Isaías 48:17', 'sabiduria', 'Te encamina por el camino que debes seguir', 10),
  v('isaias-52-7', 'Isaías 52:7', 'identidad', 'Los pies del que trae alegres nuevas', 10),
  v('isaias-55-1', 'Isaías 55:1', 'gracia', 'A todos los sedientos: Venid a las aguas', 10),
  v('isaias-55-12', 'Isaías 55:12', 'alabanza', 'Con alegría saldréis', 10),
  v('isaias-59-1', 'Isaías 59:1', 'confianza', 'No se ha acortado la mano del Señor', 10),
  v('isaias-61-10', 'Isaías 61:10', 'alabanza', 'En gran manera me gozaré en el Señor', 10),
  v('isaias-62-3', 'Isaías 62:3', 'identidad', 'Serás corona de gloria en la mano del Señor', 10),
  v('isaias-65-24', 'Isaías 65:24', 'confianza', 'Antes que clamen, responderé yo', 10),
  v('isaias-2-4', 'Isaías 2:4', 'amor', 'Volverán sus espadas en rejas de arado', 10),
  v('isaias-30-18', 'Isaías 30:18', 'confianza', 'Bienaventurados todos los que confían en él', 10),
  v('isaias-44-6', 'Isaías 44:6', 'alabanza', 'Yo soy el primero, y yo soy el postrero', 10),
  v('isaias-25-9', 'Isaías 25:9', 'esperanza', 'Este es nuestro Dios, le hemos esperado', 10),
  v('jeremias-1-7', 'Jeremías 1:7', 'identidad', 'No digas: Soy un niño', 10),
  v('jeremias-6-16', 'Jeremías 6:16', 'sabiduria', 'Preguntad por las sendas antiguas', 10),
  v('jeremias-17-8', 'Jeremías 17:8', 'esperanza', 'Como el árbol plantado junto a las aguas', 10),
  v('jeremias-18-6', 'Jeremías 18:6', 'identidad', 'Como el barro en la mano del alfarero', 10),
  v('jeremias-20-11', 'Jeremías 20:11', 'fe-y-valor', 'El Señor está conmigo como poderoso gigante', 10),
  v('jeremias-24-7', 'Jeremías 24:7', 'identidad', 'Les daré corazón para que me conozcan', 10),
  v('jeremias-15-16', 'Jeremías 15:16', 'sabiduria', 'Fueron halladas tus palabras, y yo las comí', 10),
  v('jeremias-31-13', 'Jeremías 31:13', 'esperanza', 'Cambiaré su lloro en gozo', 10),
  v('jeremias-29-7', 'Jeremías 29:7', 'amor', 'Procurad la paz de la ciudad', 10),
  v('lamentaciones-3-25', 'Lamentaciones 3:25', 'confianza', 'Bueno es el Señor a los que en él esperan', 10),
  v('ezequiel-34-26', 'Ezequiel 34:26', 'alabanza', 'Lluvias de bendición serán', 10),
  v('ezequiel-37-4', 'Ezequiel 37:4', 'esperanza', 'Huesos secos, oíd palabra del Señor', 10),
  v('ezequiel-34-11', 'Ezequiel 34:11', 'amor', 'Yo mismo iré a buscar mis ovejas', 10),
  v('daniel-3-17', 'Daniel 3:17', 'fe-y-valor', 'Nuestro Dios a quien servimos puede librarnos', 10),
  v('daniel-1-8', 'Daniel 1:8', 'identidad', 'Propuso en su corazón no contaminarse', 10),
  v('daniel-2-21', 'Daniel 2:21', 'sabiduria', 'Él muda los tiempos y las edades', 10),
  v('daniel-6-22', 'Daniel 6:22', 'fe-y-valor', 'Mi Dios envió su ángel', 10),
  v('daniel-12-3', 'Daniel 12:3', 'identidad', 'Como las estrellas a perpetua eternidad', 10),
  v('daniel-10-19', 'Daniel 10:19', 'fe-y-valor', 'Esfuérzate y aliéntate', 10),
  v('oseas-6-3', 'Oseas 6:3', 'sabiduria', 'Proseguiremos en conocer al Señor', 10),
  v('oseas-2-19', 'Oseas 2:19', 'amor', 'Te desposaré conmigo para siempre', 10),
  v('oseas-11-4', 'Oseas 11:4', 'amor', 'Con cuerdas de amor', 10),
  v('oseas-14-4', 'Oseas 14:4', 'gracia', 'Los amaré de pura gracia', 10),
  v('oseas-6-6', 'Oseas 6:6', 'gracia', 'Misericordia quiero, y no sacrificio', 10),
  v('joel-2-28', 'Joel 2:28', 'identidad', 'Derramaré mi Espíritu sobre toda carne', 10),
  v('joel-2-13', 'Joel 2:13', 'gracia', 'Rasgad vuestro corazón', 10),
  v('joel-2-21', 'Joel 2:21', 'alabanza', 'No temas; alégrate y gózate', 10),
  v('amos-5-24', 'Amós 5:24', 'sabiduria', 'Corra el juicio como las aguas', 10),
  v('jonas-2-9', 'Jonás 2:9', 'gracia', 'La salvación es del Señor', 10),
  v('miqueas-7-18', 'Miqueas 7:18', 'gracia', 'Se deleita en misericordia', 10),
  v('miqueas-7-19', 'Miqueas 7:19', 'gracia', 'En lo profundo del mar', 10),
  v('miqueas-7-7', 'Miqueas 7:7', 'esperanza', 'Esperaré al Dios de mi salvación', 10),
  v('habacuc-2-3', 'Habacuc 2:3', 'esperanza', 'Aunque tardare, espéralo', 10),
  v('habacuc-3-19', 'Habacuc 3:19', 'fe-y-valor', 'Hace mis pies como de ciervas', 10),
  v('hageo-2-4', 'Hageo 2:4', 'fe-y-valor', 'Trabajad, porque yo estoy con vosotros', 10),
  v('hageo-2-9', 'Hageo 2:9', 'esperanza', 'Daré paz en este lugar', 10),
  v('zacarias-2-8', 'Zacarías 2:8', 'identidad', 'El que os toca, toca a la niña de su ojo', 10),
  v('malaquias-3-10', 'Malaquías 3:10', 'confianza', 'Probadme ahora en esto', 10),
  v('malaquias-4-2', 'Malaquías 4:2', 'esperanza', 'Nacerá el Sol de justicia', 10),
  v('malaquias-3-6', 'Malaquías 3:6', 'confianza', 'Yo el Señor no cambio', 10),
  v('malaquias-3-17', 'Malaquías 3:17', 'identidad', 'Serán para mí especial tesoro', 10),
  v('juan-8-11', 'Juan 8:11', 'gracia', 'Ni yo te condeno; vete, y no peques más', 10),
  v('hechos-2-4', 'Hechos 2:4', 'identidad', 'Fueron todos llenos del Espíritu Santo', 10),
  v('juan-20-22', 'Juan 20:22', 'identidad', 'Recibid el Espíritu Santo', 10),
  v('isaias-11-2', 'Isaías 11:2', 'sabiduria', 'Espíritu de sabiduría y de inteligencia', 10),
  v('juan-4-10', 'Juan 4:10', 'gracia', 'Si conocieras el don de Dios', 10),
  v('mateo-6-6', 'Mateo 6:6', 'confianza', 'Entra en tu aposento', 10),
];
